// Curriculum A1 → B2
// vocab: [de, pl, example]
// test types: 'pl_de' | 'de_pl' | 'fill' | 'choice'

const CURRICULUM = {
  levels: ['A1', 'A2', 'B1', 'B2'],

  A1: {
    name: 'A1 — Grundstufe',
    namePl: 'A1 — Podstawy',
    desc: 'Podstawowe zwroty, liczby, rodzina, codzienne słownictwo',
    lessonsTotal: 12,
    lessons: [
      {
        id: 'A1_01', level: 'A1', num: 1,
        title: 'Powitania i przedstawianie się',
        intro: 'Pierwszy dzień w berlińskiej firmie IT. Wchodzisz do biura i spotykasz współpracowników przy ekspresie do kawy.',
        dialogue: [
          {s: 'Pani Schmidt', de: 'Guten Morgen! Sie sind neu hier, oder?', pl: 'Dzień dobry! Pan jest tu nowy, prawda?'},
          {s: 'Andrzej', de: 'Guten Morgen! Ja, ich heiße Andrzej. Ich komme aus Polen.', pl: 'Dzień dobry! Tak, mam na imię Andrzej. Pochodzę z Polski.'},
          {s: 'Pani Schmidt', de: 'Freut mich! Ich bin Clara Schmidt. Wie geht\'s Ihnen?', pl: 'Miło mi! Jestem Clara Schmidt. Jak się Pan miewa?'},
          {s: 'Andrzej', de: 'Gut, danke! Und Ihnen?', pl: 'Dobrze, dziękuję! A Pani?'},
          {s: 'Pani Schmidt', de: 'Auch gut, danke. Willkommen im Team!', pl: 'Też dobrze, dziękuję. Witamy w zespole!'},
          {s: 'Andrzej', de: 'Danke sehr! Auf Wiedersehen!', pl: 'Dziękuję bardzo! Do widzenia!'}
        ],
        cultural: 'W Niemczech per "Sie" (wielka litera) mówi się do przełożonych i nieznajomych. Przejście na "du" następuje dopiero po zaproszeniu — zazwyczaj inicjuje je starsza ranga.',
        vocab: [
          ['Hallo', 'Cześć', 'Hallo, wie geht\'s?'],
          ['Guten Morgen', 'Dzień dobry (rano)', 'Guten Morgen! Haben Sie gut geschlafen?'],
          ['Guten Tag', 'Dzień dobry', 'Guten Tag, ich bin Andrzej.'],
          ['Guten Abend', 'Dobry wieczór', 'Guten Abend! Wie war Ihr Tag?'],
          ['Gute Nacht', 'Dobranoc', 'Gute Nacht, schlaf gut!'],
          ['Auf Wiedersehen', 'Do widzenia', 'Auf Wiedersehen und viel Erfolg!'],
          ['Tschüss', 'Pa / Do widzenia', 'Tschüss, bis morgen!'],
          ['Bitte', 'Proszę', 'Ein Kaffee, bitte.'],
          ['Danke', 'Dziękuję', 'Danke sehr!'],
          ['Entschuldigung', 'Przepraszam', 'Entschuldigung, wo ist der Bahnhof?'],
          ['Ja', 'Tak', 'Ja, natürlich!'],
          ['Nein', 'Nie', 'Nein, danke.'],
          ['Ich heiße...', 'Mam na imię...', 'Ich heiße Andrzej.'],
          ['Ich komme aus Polen', 'Pochodzę z Polski', 'Ich komme aus Polen, aus Warschau.'],
          ['Wie geht\'s?', 'Jak się masz?', 'Wie geht\'s? – Gut, danke!'],
          ['Gut', 'Dobrze', 'Mir geht es gut.'],
          ['Nicht so gut', 'Niezbyt dobrze', 'Heute nicht so gut.'],
          ['Freut mich!', 'Miło mi!', 'Freut mich, Sie kennenzulernen!']
        ],
        grammar: {
          title: 'Koniugacja "sein" (być) + zaimki osobowe',
          content: 'ich bin • du bist • er/sie/es ist • wir sind • ihr seid • sie/Sie sind\n\nZaimki: ich (ja) • du (ty) • er (on) • sie (ona) • wir (my) • Sie (Pan/i)',
          note: 'Sie (wielka litera) = forma grzecznościowa. Wie heißen Sie? – formalnie. Wie heißt du? – nieformalne.'
        },
        tests: [
          {type:'pl_de', q:'Cześć', a:'Hallo'},
          {type:'pl_de', q:'Dziękuję', a:'Danke'},
          {type:'pl_de', q:'Przepraszam', a:'Entschuldigung'},
          {type:'de_pl', q:'Guten Morgen', a:'Dzień dobry (rano)'},
          {type:'de_pl', q:'Auf Wiedersehen', a:'Do widzenia'},
          {type:'de_pl', q:'Freut mich!', a:'Miło mi!'},
          {type:'fill', q:'Ich ___ Andrzej. (heißen)', a:'heiße', hint:'Koniugacja: heißen → ich...'},
          {type:'fill', q:'Ich ___ aus Polen. (kommen)', a:'komme', hint:'Koniugacja: kommen → ich...'},
          {type:'choice', q:'Jak powiemy "jesteście" po niemiecku?', a:'ihr seid',
           opts:['wir sind','ihr seid','sie sind','du bist']},
          {type:'choice', q:'Formalne "do widzenia" to:', a:'Auf Wiedersehen',
           opts:['Tschüss','Ciao','Auf Wiedersehen','Gute Nacht']}
        ]
      },
      {
        id: 'A1_02', level: 'A1', num: 2,
        title: 'Liczby 1–100',
        intro: 'Przerwa obiadowa. Zamawiasz lunch w firmowej kantynie i płacisz przy kasie.',
        dialogue: [
          {s: 'Andrzej', de: 'Ich hätte gern ein Mittagessen, bitte. Was kostet das?', pl: 'Poproszę jeden obiad. Ile to kosztuje?'},
          {s: 'Kasjerka', de: 'Das kostet acht Euro fünfzig.', pl: 'To kosztuje osiem euro pięćdziesiąt.'},
          {s: 'Andrzej', de: 'Ich habe nur zwanzig Euro. Haben Sie Wechselgeld?', pl: 'Mam tylko dwadzieścia euro. Czy ma Pani resztę?'},
          {s: 'Kasjerka', de: 'Ja, natürlich. Das macht elf Euro fünfzig zurück.', pl: 'Tak, oczywiście. To będzie jedenaście euro pięćdziesiąt reszty.'},
          {s: 'Andrzej', de: 'Danke sehr! Tisch drei ist frei, oder?', pl: 'Dziękuję bardzo! Stolik numer trzy jest wolny, prawda?'},
          {s: 'Kasjerka', de: 'Ja, Tisch drei und vier sind frei. Guten Appetit!', pl: 'Tak, stoliki trzy i cztery są wolne. Smacznego!'}
        ],
        cultural: 'W Niemczech ceny podaje się w formie "acht Euro fünfzig" (8,50 €). Napiwki nie są obowiązkowe, ale zwyczajowo zaokrągla się kwotę w górę.',
        vocab: [
          ['null', 'zero', 'Die Telefonnummer ist null...'],
          ['eins', 'jeden', 'Ich habe eins.'],
          ['zwei', 'dwa', 'Zwei Kaffee, bitte.'],
          ['drei', 'trzy', 'Drei Tage.'],
          ['vier', 'cztery', 'Vier Personen.'],
          ['fünf', 'pięć', 'Fünf Euro.'],
          ['sechs', 'sześć', 'Sechs Stunden.'],
          ['sieben', 'siedem', 'Sieben Tage hat die Woche.'],
          ['acht', 'osiem', 'Acht Uhr morgens.'],
          ['neun', 'dziewięć', 'Neun Monate.'],
          ['zehn', 'dziesięć', 'Zehn Minuten.'],
          ['zwanzig', 'dwadzieścia', 'Zwanzig Euro.'],
          ['dreißig', 'trzydzieści', 'Dreißig Grad.'],
          ['vierzig', 'czterdzieści', 'Vierzig Kilometer.'],
          ['fünfzig', 'pięćdziesiąt', 'Fünfzig Prozent.'],
          ['hundert', 'sto', 'Hundert Euro.'],
          ['erste', 'pierwszy', 'Der erste Tag.'],
          ['zweite', 'drugi', 'Das zweite Mal.'],
          ['Wie viel?', 'Ile?', 'Wie viel kostet das?'],
          ['Das kostet...', 'To kosztuje...', 'Das kostet fünf Euro.']
        ],
        grammar: {
          title: 'Tworzenie liczb 13–19 i dziesiątek',
          content: '13–19: dodaj "-zehn": dreizehn, vierzehn, fünfzehn...\n\nDziesiątki: zwanzig, dreißig, vierzig, fünfzig, sechzig, siebzig, achtzig, neunzig\n\nLiczby złożone: 21 = einundzwanzig (najpierw jedności + "und" + dziesiątka)',
          note: 'Wyjątek: 1 = eins (samodzielnie), ale 21 = einundzwanzig (bez "s")'
        },
        tests: [
          {type:'de_pl', q:'fünfzehn', a:'piętnaście'},
          {type:'de_pl', q:'dreißig', a:'trzydzieści'},
          {type:'pl_de', q:'czterdzieści pięć', a:'fünfundvierzig'},
          {type:'pl_de', q:'sto', a:'hundert'},
          {type:'fill', q:'Wie viel ___ das? (kosten)', a:'kostet', hint:'3. osoba l.poj.'},
          {type:'fill', q:'___ + zwanzig = einundzwanzig', a:'ein', hint:'Najpierw jedności...'},
          {type:'choice', q:'Jak powiemy "osiemnaście"?', a:'achtzehn',
           opts:['achzehn','achtzehn','achtzehen','achtzig']},
          {type:'choice', q:'"Das ___ fünf Euro." (kosztuje)', a:'kostet',
           opts:['kosten','kostet','kostest','koste']},
          {type:'pl_de', q:'siedemdziesiąt', a:'siebzig'},
          {type:'de_pl', q:'neunundneunzig', a:'dziewięćdziesiąt dziewięć'}
        ]
      },
      {
        id: 'A1_03', level: 'A1', num: 3,
        title: 'Kolory i przymiotniki podstawowe',
        intro: 'Spotkanie projektowe w biurze. Omawiasz nowe logo klienta z koleżanką z zespołu designu.',
        dialogue: [
          {s: 'Lisa', de: 'Andrzej, was denkst du über unser neues Logo?', pl: 'Andrzej, co myślisz o naszym nowym logo?'},
          {s: 'Andrzej', de: 'Es ist schön! Aber die Farbe ist zu dunkel. Kann es blau sein?', pl: 'Jest piękne! Ale kolor jest za ciemny. Czy może być niebieskie?'},
          {s: 'Lisa', de: 'Blau? Das alte Logo war auch blau. Der Kunde möchte etwas Neues.', pl: 'Niebieskie? Stare logo też było niebieskie. Klient chce czegoś nowego.'},
          {s: 'Andrzej', de: 'Dann vielleicht grün? Grün ist modern und interessant.', pl: 'Może więc zielone? Zielony jest nowoczesny i interesujący.'},
          {s: 'Lisa', de: 'Gute Idee! Aber nicht zu hell — ein dunkles Grün. Das ist elegant.', pl: 'Dobry pomysł! Ale nie za jasny — ciemna zieleń. To eleganckie.'},
          {s: 'Andrzej', de: 'Perfekt! Und die Schrift — weiß auf grünem Hintergrund.', pl: 'Idealnie! I czcionka — biała na zielonym tle.'}
        ],
        cultural: 'Niemcy są znani z precyzji w komunikacji — w dyskusjach biznesowych oczekuje się konkretnych propozycji, a nie ogólnych komentarzy.',
        vocab: [
          ['rot', 'czerwony', 'Das Auto ist rot.'],
          ['blau', 'niebieski', 'Der Himmel ist blau.'],
          ['grün', 'zielony', 'Das Gras ist grün.'],
          ['gelb', 'żółty', 'Die Banane ist gelb.'],
          ['weiß', 'biały', 'Der Schnee ist weiß.'],
          ['schwarz', 'czarny', 'Die Katze ist schwarz.'],
          ['grau', 'szary', 'Der Himmel ist grau.'],
          ['braun', 'brązowy', 'Der Kaffee ist braun.'],
          ['orange', 'pomarańczowy', 'Die Orange ist orange.'],
          ['lila', 'fioletowy', 'Das Hemd ist lila.'],
          ['rosa', 'różowy', 'Die Blume ist rosa.'],
          ['groß', 'duży', 'Das Haus ist groß.'],
          ['klein', 'mały', 'Das Kind ist klein.'],
          ['alt', 'stary', 'Der Mann ist alt.'],
          ['neu / jung', 'nowy / młody', 'Das Auto ist neu.'],
          ['gut', 'dobry', 'Das Essen ist gut.'],
          ['schlecht', 'zły / niedobry', 'Das Wetter ist schlecht.'],
          ['schön', 'piękny', 'Die Stadt ist schön.'],
          ['interessant', 'interesujący', 'Das Buch ist interessant.'],
          ['teuer / billig', 'drogi / tani', 'Das ist teuer!']
        ],
        grammar: {
          title: 'Przymiotniki orzecznikowe vs. atrybutywne',
          content: 'Orzecznikowe (po "sein"): Das Auto ist rot. → bez końcówki\n\nAtrybutywne (przed rzeczownikiem): Das rote Auto. → z końcówką\n\nRodzajnik nieokreślony: ein roter Tisch / eine rote Lampe / ein rotes Auto',
          note: 'Na razie koncentruj się na formie orzecznikowej — to jest A1!'
        },
        tests: [
          {type:'de_pl', q:'weiß', a:'biały'},
          {type:'de_pl', q:'groß', a:'duży'},
          {type:'pl_de', q:'niebieski', a:'blau'},
          {type:'pl_de', q:'piękny', a:'schön'},
          {type:'fill', q:'Das Auto ist ___. (czerwone)', a:'rot'},
          {type:'fill', q:'Die Katze ist ___. (mała)', a:'klein'},
          {type:'choice', q:'Które słowo oznacza "interesujący"?', a:'interessant',
           opts:['interessant','interessiert','Interesse','interessieren']},
          {type:'choice', q:'"Tani" to:', a:'billig', opts:['teuer','billig','schön','gut']},
          {type:'pl_de', q:'szary', a:'grau'},
          {type:'de_pl', q:'schlecht', a:'zły / niedobry'}
        ]
      },
      {
        id: 'A1_04', level: 'A1', num: 4,
        title: 'Rodzina',
        intro: 'Kawa po spotkaniu. Kolega z Hamburga — Thomas — pyta Cię o rodzinę. To pierwszy bardziej osobisty kontakt w nowej firmie.',
        dialogue: [
          {s: 'Thomas', de: 'Andrzej, hast du Familie in Polen?', pl: 'Andrzej, czy masz rodzinę w Polsce?'},
          {s: 'Andrzej', de: 'Ja, meine Eltern wohnen in Warschau. Ich habe auch eine Schwester.', pl: 'Tak, moi rodzice mieszkają w Warszawie. Mam też siostrę.'},
          {s: 'Thomas', de: 'Ist sie verheiratet?', pl: 'Czy ona jest zamężna?'},
          {s: 'Andrzej', de: 'Ja, sie hat einen Mann und ein Kind — einen Sohn. Er ist drei Jahre alt.', pl: 'Tak, ma męża i dziecko — syna. Ma trzy lata.'},
          {s: 'Thomas', de: 'Wie süß! Meine Frau und ich haben zwei Töchter.', pl: 'Jakie słodkie! Moja żona i ja mamy dwie córki.'},
          {s: 'Andrzej', de: 'Wie alt sind sie?', pl: 'Ile mają lat?'},
          {s: 'Thomas', de: 'Fünf und acht. Sie sind mein ganzes Leben!', pl: 'Pięć i osiem. Są całym moim życiem!'}
        ],
        cultural: 'W Niemczech pytanie o rodzinę jest akceptowalne przy bliższym poznaniu. Niemcy cenią prywatność, więc takie rozmowy zaczynają się zazwyczaj po pewnym czasie znajomości.',
        vocab: [
          ['die Familie', 'rodzina', 'Meine Familie ist groß.'],
          ['die Mutter', 'matka', 'Meine Mutter heißt Anna.'],
          ['der Vater', 'ojciec', 'Mein Vater arbeitet in Warschau.'],
          ['die Eltern', 'rodzice', 'Meine Eltern sind verheiratet.'],
          ['der Bruder', 'brat', 'Ich habe einen Bruder.'],
          ['die Schwester', 'siostra', 'Meine Schwester ist jung.'],
          ['der Sohn', 'syn', 'Sie hat einen Sohn.'],
          ['die Tochter', 'córka', 'Meine Tochter ist 5 Jahre alt.'],
          ['die Großmutter / Oma', 'babcia', 'Meine Oma macht guten Kuchen.'],
          ['der Großvater / Opa', 'dziadek', 'Mein Opa ist 80 Jahre alt.'],
          ['der Mann', 'mąż / mężczyzna', 'Mein Mann heißt Thomas.'],
          ['die Frau', 'żona / kobieta', 'Meine Frau kommt aus Berlin.'],
          ['das Kind', 'dziecko', 'Das Kind spielt im Garten.'],
          ['der Onkel', 'wujek', 'Mein Onkel lebt in Hamburg.'],
          ['die Tante', 'ciotka', 'Meine Tante kocht sehr gut.'],
          ['verheiratet', 'żonaty / zamężna', 'Sie sind verheiratet.'],
          ['ledig', 'wolny stan', 'Er ist noch ledig.'],
          ['das Baby', 'niemowlę', 'Das Baby schläft.']
        ],
        grammar: {
          title: 'Rodzajniki + zaimki dzierżawcze (mein/meine)',
          content: 'Rodzajniki: der (m) • die (f) • das (n) • die (pl)\n\nMein Vater (m) • meine Mutter (f) • mein Kind (n)\ndein Vater • deine Mutter • dein Kind\n\nPytanie o rodzinę: Hast du Geschwister? (Czy masz rodzeństwo?)',
          note: 'Geschwister = rodzeństwo (bez rozróżnienia na brata/siostrę w l.mn.)'
        },
        tests: [
          {type:'de_pl', q:'die Geschwister', a:'rodzeństwo'},
          {type:'de_pl', q:'verheiratet', a:'żonaty / zamężna'},
          {type:'pl_de', q:'babcia', a:'die Großmutter'},
          {type:'pl_de', q:'córka', a:'die Tochter'},
          {type:'fill', q:'___ Mutter heißt Anna. (mój)', a:'Meine'},
          {type:'fill', q:'Das ___ spielt im Garten. (dziecko)', a:'Kind'},
          {type:'choice', q:'Rodzajnik przy "Vater" to:', a:'der',
           opts:['der','die','das','ein']},
          {type:'choice', q:'"Ledig" znaczy:', a:'wolny stan',
           opts:['żonaty','wolny stan','rozwiedziony','wdowiec']},
          {type:'pl_de', q:'wujek', a:'der Onkel'},
          {type:'de_pl', q:'die Frau', a:'żona / kobieta'}
        ]
      },
      {
        id: 'A1_05', level: 'A1', num: 5,
        title: 'Jedzenie i napoje',
        intro: 'Piątek, 18:00. Cały zespół idzie na kolację do pobliskiej restauracji, żeby poznać nowego kolegę — Ciebie.',
        dialogue: [
          {s: 'Kelner', de: 'Guten Abend! Was möchten Sie trinken?', pl: 'Dobry wieczór! Co chcielibyście Państwo do picia?'},
          {s: 'Lisa', de: 'Ich nehme ein Wasser, bitte.', pl: 'Poproszę wodę.'},
          {s: 'Andrzej', de: 'Ich hätte gern ein Bier. Was empfehlen Sie zum Essen?', pl: 'Poproszę piwo. Co Pan poleca do jedzenia?'},
          {s: 'Kelner', de: 'Das Schnitzel mit Kartoffeln ist sehr gut heute.', pl: 'Sznycel z ziemniakami jest dziś bardzo dobry.'},
          {s: 'Andrzej', de: 'Gut, ich esse das Schnitzel. Und einen Salat dazu, bitte.', pl: 'Dobrze, wezmę sznycel. I sałatkę do tego, proszę.'},
          {s: 'Thomas', de: 'Ich bin Vegetarier. Gibt es etwas ohne Fleisch?', pl: 'Jestem wegetarianinem. Czy jest coś bez mięsa?'},
          {s: 'Kelner', de: 'Natürlich! Die Gemüsesuppe und der Käsekuchen sind sehr zu empfehlen.', pl: 'Oczywiście! Polecam zupę warzywną i sernik.'}
        ],
        cultural: 'W Niemczech popularne jest osobne płacenie (getrennte Rechnung). Powiedzenie "Ich zahle für mich" (płacę za siebie) jest zupełnie normalne i nie jest niegrzeczne.',
        vocab: [
          ['das Brot', 'chleb', 'Ich esse Brot zum Frühstück.'],
          ['die Butter', 'masło', 'Brot mit Butter, bitte.'],
          ['der Käse', 'ser', 'Ich mag Käse sehr.'],
          ['das Fleisch', 'mięso', 'Er isst kein Fleisch.'],
          ['der Fisch', 'ryba', 'Fisch ist gesund.'],
          ['das Gemüse', 'warzywa', 'Ich esse viel Gemüse.'],
          ['das Obst', 'owoce', 'Obst ist lecker.'],
          ['die Milch', 'mleko', 'Ein Glas Milch, bitte.'],
          ['das Wasser', 'woda', 'Ich trinke viel Wasser.'],
          ['der Kaffee', 'kawa', 'Morgens trinke ich Kaffee.'],
          ['der Tee', 'herbata', 'Eine Tasse Tee, bitte.'],
          ['das Bier', 'piwo', 'Ein Bier, bitte.'],
          ['der Saft', 'sok', 'Orangensaft ist mein Lieblingsgetränk.'],
          ['essen', 'jeść', 'Was isst du gern?'],
          ['trinken', 'pić', 'Ich trinke Kaffee.'],
          ['kochen', 'gotować', 'Meine Mutter kocht gut.'],
          ['lecker', 'pyszny', 'Das ist sehr lecker!'],
          ['hungrig', 'głodny', 'Ich bin hungrig.'],
          ['satt', 'najedzony', 'Ich bin satt, danke.'],
          ['das Frühstück', 'śniadanie', 'Was isst du zum Frühstück?']
        ],
        grammar: {
          title: 'Koniugacja "essen" i "trinken" + przypadek Akkusativ',
          content: 'essen: ich esse • du isst • er/sie isst • wir essen • ihr esst • sie essen\ntrinken: ich trinke • du trinkst • er trinkt...\n\nAkkusativ po "essen/trinken/mögen":\nIch esse den Käse (m→den) • die Butter (f→die) • das Brot (n→das)',
          note: 'Mögen: ich mag • du magst • er mag (lubić) — używane częściej niż "essen gern"'
        },
        tests: [
          {type:'de_pl', q:'das Frühstück', a:'śniadanie'},
          {type:'de_pl', q:'hungrig', a:'głodny'},
          {type:'pl_de', q:'warzywa', a:'das Gemüse'},
          {type:'pl_de', q:'pić', a:'trinken'},
          {type:'fill', q:'Er ___ kein Fleisch. (essen)', a:'isst'},
          {type:'fill', q:'Das ___ sehr lecker! (sein)', a:'ist'},
          {type:'choice', q:'Forma "essen" dla "du" to:', a:'isst',
           opts:['esst','isst','essst','ißt']},
          {type:'choice', q:'"Satt" oznacza:', a:'najedzony',
           opts:['głodny','spragniony','najedzony','zmęczony']},
          {type:'pl_de', q:'pyszny', a:'lecker'},
          {type:'de_pl', q:'kochen', a:'gotować'}
        ]
      },
      {
        id: 'A1_06', level: 'A1', num: 6,
        title: 'Czas — dni, miesiące, godziny',
        intro: 'Poniedziałek rano. Ustalasz harmonogram sprint review z koleżanką Miną przez firmowy czat.',
        dialogue: [
          {s: 'Mina', de: 'Hallo Andrzej! Wann passt dir das Sprint Review?', pl: 'Cześć Andrzej! Kiedy pasuje Ci sprint review?'},
          {s: 'Andrzej', de: 'Am Mittwoch bin ich frei. Um wie viel Uhr?', pl: 'W środę jestem wolny. O której godzinie?'},
          {s: 'Mina', de: 'Um zehn Uhr? Das Meeting dauert etwa eine Stunde.', pl: 'O dziesiątej? Spotkanie trwa około godziny.'},
          {s: 'Andrzej', de: 'Perfekt. Und der Deployment — wann ist das?', pl: 'Idealnie. A deploy — kiedy to jest?'},
          {s: 'Mina', de: 'Am Freitag, den dreizehnten Mai. Aber Freitag der Dreizehnte ist Pech!', pl: 'W piątek, trzynastego maja. Ale piątek trzynastego to pech!'},
          {s: 'Andrzej', de: 'Ha! In Polen auch. Bis Mittwoch dann!', pl: 'Ha! W Polsce też. Do środy więc!'}
        ],
        cultural: 'W Niemczech punktualność jest niezwykle ważna. Spóźnienie o 5 minut bez ostrzeżenia jest uważane za brak szacunku — zawsze uprzedź SMS-em lub emailem.',
        vocab: [
          ['Montag', 'poniedziałek', 'Am Montag arbeite ich.'],
          ['Dienstag', 'wtorek', 'Dienstag ist ein Arbeitstag.'],
          ['Mittwoch', 'środa', 'Am Mittwoch haben wir ein Meeting.'],
          ['Donnerstag', 'czwartek', 'Donnerstag ist fast Freitag!'],
          ['Freitag', 'piątek', 'Am Freitag gehe ich früh nach Hause.'],
          ['Samstag', 'sobota', 'Am Samstag schlafe ich lange.'],
          ['Sonntag', 'niedziela', 'Sonntag ist ein Ruhetag.'],
          ['heute', 'dzisiaj', 'Heute ist Montag.'],
          ['morgen', 'jutro', 'Morgen arbeite ich von zu Hause.'],
          ['gestern', 'wczoraj', 'Gestern war ich krank.'],
          ['jetzt', 'teraz', 'Jetzt arbeite ich.'],
          ['die Uhr', 'godzina / zegar', 'Wie viel Uhr ist es?'],
          ['Es ist... Uhr', 'Jest godzina...', 'Es ist neun Uhr.'],
          ['früh', 'wcześnie / rano', 'Ich stehe früh auf.'],
          ['spät', 'późno', 'Es ist schon spät.'],
          ['Januar', 'styczeń', 'Im Januar ist es kalt.'],
          ['März', 'marzec', 'Im März beginnt der Frühling.'],
          ['das Jahr', 'rok', 'Das Jahr hat 365 Tage.'],
          ['der Monat', 'miesiąc', 'Ein Monat hat 30 Tage.'],
          ['die Woche', 'tydzień', 'Die Woche hat 7 Tage.']
        ],
        grammar: {
          title: 'Wyrażanie czasu: am / um / im',
          content: 'Dni tygodnia: am Montag, am Dienstag...\nMiesiące: im Januar, im Februar...\nGodziny: um 9 Uhr, um halb zehn (9:30), um Viertel nach acht (8:15)\n\nEs ist 9 Uhr. / Es ist halb zehn. / Es ist Viertel vor zehn.',
          note: 'halb zehn = pół do dziesiątej = 9:30 (UWAGA: nie "pół dziesiątej"!)'
        },
        tests: [
          {type:'de_pl', q:'Mittwoch', a:'środa'},
          {type:'de_pl', q:'gestern', a:'wczoraj'},
          {type:'pl_de', q:'niedziela', a:'Sonntag'},
          {type:'pl_de', q:'jutro', a:'morgen'},
          {type:'fill', q:'___ Montag arbeite ich. (w poniedziałek)', a:'Am'},
          {type:'fill', q:'Es ist ___ Uhr. (9)', a:'neun'},
          {type:'choice', q:'"Halb zehn" oznacza:', a:'9:30',
           opts:['10:30','9:30','10:15','9:15']},
          {type:'choice', q:'W miesiącach używamy przyimka:', a:'im',
           opts:['am','im','um','in']},
          {type:'pl_de', q:'tydzień', a:'die Woche'},
          {type:'de_pl', q:'früh', a:'wcześnie / rano'}
        ]
      },
      {
        id: 'A1_07', level: 'A1', num: 7,
        title: 'Dom i meble',
        intro: 'Przeprowadzasz się do Berlina. Oglądasz mieszkanie z agentem nieruchomości.',
        dialogue: [
          {s: 'Agent', de: 'Herzlich willkommen! Das ist Ihr neues Apartment — 60 Quadratmeter.', pl: 'Serdecznie witamy! To jest Pana nowe mieszkanie — 60 metrów kwadratowych.'},
          {s: 'Andrzej', de: 'Schön! Wo ist die Küche?', pl: 'Pięknie! Gdzie jest kuchnia?'},
          {s: 'Agent', de: 'Die Küche ist links, das Badezimmer ist rechts, und das Schlafzimmer ist geradeaus.', pl: 'Kuchnia jest po lewej, łazienka po prawej, a sypialnia prosto.'},
          {s: 'Andrzej', de: 'Gibt es einen Tisch und Stühle?', pl: 'Czy jest stół i krzesła?'},
          {s: 'Agent', de: 'Ja, im Wohnzimmer. Es gibt auch ein Sofa und einen Schrank.', pl: 'Tak, w salonie. Jest też kanapa i szafa.'},
          {s: 'Andrzej', de: 'Super! Ich nehme die Wohnung.', pl: 'Super! Biorę to mieszkanie.'}
        ],
        cultural: 'W Niemczech wynajem mieszkania wymaga często Schufa (historia kredytowa) i dwóch miesięcy kaucji (Kaution). Mieszkania z meblami (möbliert) są rzadsze niż w Polsce.',
        vocab: [
          ['das Haus', 'dom', 'Ich wohne in einem Haus.'],
          ['die Wohnung', 'mieszkanie', 'Die Wohnung hat drei Zimmer.'],
          ['das Zimmer', 'pokój', 'Mein Zimmer ist groß.'],
          ['die Küche', 'kuchnia', 'Ich koche in der Küche.'],
          ['das Badezimmer', 'łazienka', 'Das Badezimmer ist klein.'],
          ['das Schlafzimmer', 'sypialnia', 'Das Schlafzimmer ist ruhig.'],
          ['das Wohnzimmer', 'salon', 'Wir sitzen im Wohnzimmer.'],
          ['der Tisch', 'stół', 'Der Tisch ist aus Holz.'],
          ['der Stuhl', 'krzesło', 'Bitte nehmen Sie Platz!'],
          ['das Bett', 'łóżko', 'Das Bett ist sehr bequem.'],
          ['der Schrank', 'szafa', 'Meine Kleider sind im Schrank.'],
          ['die Tür', 'drzwi', 'Bitte schließ die Tür!'],
          ['das Fenster', 'okno', 'Das Fenster ist offen.'],
          ['wohnen', 'mieszkać', 'Ich wohne in Warschau.'],
          ['die Miete', 'czynsz', 'Die Miete ist teuer.'],
          ['das Sofa', 'sofa', 'Ich sitze auf dem Sofa.'],
          ['der Kühlschrank', 'lodówka', 'Das Essen ist im Kühlschrank.'],
          ['das Licht', 'światło', 'Mach das Licht an!']
        ],
        grammar: {
          title: 'Przyimki miejsca: in / an / auf + Dativ',
          content: 'Gdzie? (Dativ): in dem → im / an dem → am\nIch bin im Zimmer. • Das Buch ist auf dem Tisch. • Das Bild hängt an der Wand.\n\nDativ: der→dem • die→der • das→dem',
          note: 'Wohin? (Akkusativ): Ich gehe ins Zimmer. • Ich lege das Buch auf den Tisch.'
        },
        tests: [
          {type:'de_pl', q:'das Wohnzimmer', a:'salon'},
          {type:'de_pl', q:'der Kühlschrank', a:'lodówka'},
          {type:'pl_de', q:'sypialnia', a:'das Schlafzimmer'},
          {type:'pl_de', q:'mieszkać', a:'wohnen'},
          {type:'fill', q:'Ich wohne ___ Warschau. (w)', a:'in'},
          {type:'fill', q:'Das Essen ist ___ Kühlschrank. (im/w)', a:'im'},
          {type:'choice', q:'Gdzie? → przyimek + Dativ. "Der Tisch" → Dativ:', a:'dem Tisch',
           opts:['den Tisch','dem Tisch','der Tisch','des Tisches']},
          {type:'choice', q:'"Die Miete ist teuer" znaczy:', a:'Czynsz jest drogi',
           opts:['Meble są drogie','Czynsz jest drogi','Dom jest duży','Mieszkanie jest nowe']},
          {type:'pl_de', q:'okno', a:'das Fenster'},
          {type:'de_pl', q:'die Tür', a:'drzwi'}
        ]
      },
      {
        id: 'A1_08', level: 'A1', num: 8,
        title: 'Praca i zawody',
        intro: 'HR przedstawia Cię nowemu zespołowi na porannym stand-upie. Pytają o Twoje doświadczenie.',
        dialogue: [
          {s: 'HR Anna', de: 'Team, das ist Andrzej — unser neuer Softwareentwickler aus Polen.', pl: 'Zespół, to jest Andrzej — nasz nowy programista z Polski.'},
          {s: 'Andrzej', de: 'Hallo alle! Ich bin Entwickler und arbeite mit Python und JavaScript.', pl: 'Cześć wszystkim! Jestem programistą i pracuję z Pythonem i JavaScriptem.'},
          {s: 'Kollege Ben', de: 'Toll! Wie lange arbeitest du schon als Entwickler?', pl: 'Super! Jak długo pracujesz już jako programista?'},
          {s: 'Andrzej', de: 'Seit fünf Jahren. Vorher war ich Student in Warschau.', pl: 'Od pięciu lat. Wcześniej byłem studentem w Warszawie.'},
          {s: 'HR Anna', de: 'Andrzej ist auch unser Kontakt für das polnische Büro.', pl: 'Andrzej jest też naszym kontaktem dla polskiego biura.'},
          {s: 'Andrzej', de: 'Genau! Ich spreche Polnisch, Englisch und jetzt lerne ich Deutsch.', pl: 'Dokładnie! Mówię po polsku, angielsku i teraz uczę się niemieckiego.'}
        ],
        cultural: 'Na niemieckich stand-upach obowiązuje zasada krótkich, rzeczowych wypowiedzi. "Was habe ich gestern gemacht? Was mache ich heute? Gibt es Blocker?" — i koniec.',
        vocab: [
          ['die Arbeit', 'praca', 'Die Arbeit beginnt um 9 Uhr.'],
          ['arbeiten', 'pracować', 'Ich arbeite bei einer IT-Firma.'],
          ['der Arzt / die Ärztin', 'lekarz / lekarka', 'Mein Bruder ist Arzt.'],
          ['der Lehrer / die Lehrerin', 'nauczyciel/ka', 'Sie ist Lehrerin in Berlin.'],
          ['der Ingenieur', 'inżynier', 'Er arbeitet als Ingenieur.'],
          ['der Programmierer', 'programista', 'Ich bin Programmierer.'],
          ['der Kaufmann', 'handlowiec', 'Er ist Kaufmann bei BMW.'],
          ['der Manager', 'menadżer', 'Sie ist Manager bei Siemens.'],
          ['das Büro', 'biuro', 'Ich arbeite im Büro.'],
          ['die Firma', 'firma', 'Meine Firma ist in Warschau.'],
          ['der Chef / die Chefin', 'szef / szefowa', 'Mein Chef ist nett.'],
          ['der Kollege / die Kollegin', 'kolega / koleżanka', 'Meine Kollegin spricht Deutsch.'],
          ['das Gehalt', 'wynagrodzenie', 'Das Gehalt ist gut.'],
          ['die Besprechung', 'spotkanie / narada', 'Wir haben eine Besprechung.'],
          ['Vollzeit / Teilzeit', 'pełny / niepełny etat', 'Ich arbeite Vollzeit.'],
          ['das Homeoffice', 'praca zdalna', 'Heute arbeite ich im Homeoffice.'],
          ['der Vertrag', 'umowa', 'Ich habe einen Vertrag.'],
          ['die Erfahrung', 'doświadczenie', 'Er hat viel Erfahrung.']
        ],
        grammar: {
          title: 'Zawody bez rodzajnika + "als" (jako)',
          content: 'Zawody po "sein": Ich bin Programmierer. (BEZ rodzajnika!)\n\nZawody po "arbeiten als": Ich arbeite als Ingenieur.\n\nForma żeńska: dodaj "-in": der Lehrer → die Lehrerin\nder Kollege → die Kollegin (nieregularne!)',
          note: 'W CV piszemy: Programmierer mit 5 Jahren Erfahrung bei...'
        },
        tests: [
          {type:'de_pl', q:'die Besprechung', a:'spotkanie / narada'},
          {type:'de_pl', q:'das Gehalt', a:'wynagrodzenie'},
          {type:'pl_de', q:'praca zdalna', a:'das Homeoffice'},
          {type:'pl_de', q:'umowa', a:'der Vertrag'},
          {type:'fill', q:'Ich ___ Programmierer. (sein)', a:'bin'},
          {type:'fill', q:'Er arbeitet ___ Ingenieur. (jako)', a:'als'},
          {type:'choice', q:'Żeńska forma "der Arzt" to:', a:'die Ärztin',
           opts:['die Arzt','die Arztin','die Ärztin','die Ärzten']},
          {type:'choice', q:'Zawód po "sein" w zdaniu:', a:'Ich bin Lehrer.',
           opts:['Ich bin ein Lehrer.','Ich bin Lehrer.','Ich bin der Lehrer.','Ich bin als Lehrer.']},
          {type:'pl_de', q:'szef', a:'der Chef'},
          {type:'de_pl', q:'die Erfahrung', a:'doświadczenie'}
        ]
      },
      {
        id: 'A1_09', level: 'A1', num: 9,
        title: 'Zakupy i pieniądze',
        intro: 'Sobota. Idziesz do pobliskiego Rewe po zakupy na tydzień. Nie masz karty — tylko gotówkę.',
        dialogue: [
          {s: 'Andrzej', de: 'Entschuldigung, wo finde ich den Käse?', pl: 'Przepraszam, gdzie znajdę ser?'},
          {s: 'Mitarbeiter', de: 'Der Käse ist im Gang drei, links neben der Milch.', pl: 'Ser jest w alejce trzeciej, po lewej stronie obok mleka.'},
          {s: 'Andrzej', de: 'Danke! Und haben Sie Bio-Tomaten?', pl: 'Dziękuję! I czy macie pomidory bio?'},
          {s: 'Mitarbeiter', de: 'Ja, in der Gemüseabteilung, gleich am Eingang.', pl: 'Tak, w dziale warzywnym, zaraz przy wejściu.'},
          {s: 'Kassiererin', de: 'Das macht zusammen siebenundzwanzig Euro achtzig.', pl: 'Razem to będzie dwadzieścia siedem euro osiemdziesiąt.'},
          {s: 'Andrzej', de: 'Ich zahle mit Karte. Oh — geht das hier nicht?', pl: 'Płacę kartą. O — nie można tu tak?'},
          {s: 'Kassiererin', de: 'Tut mir leid, nur Bargeld. Der Automat ist kaputt.', pl: 'Przepraszam, tylko gotówka. Automat jest zepsuty.'}
        ],
        cultural: 'Niemcy słyną z przywiązania do gotówki (Bargeld). Wiele małych sklepów, restauracji i targowisk nadal nie akceptuje kart. "Nur Bargeld" to bardzo popularne ostrzeżenie.',
        vocab: [
          ['der Supermarkt', 'supermarket', 'Ich kaufe im Supermarkt ein.'],
          ['der Laden', 'sklep', 'Der Laden ist geschlossen.'],
          ['kaufen', 'kupować', 'Ich kaufe ein neues Handy.'],
          ['bezahlen', 'płacić', 'Wie möchten Sie bezahlen?'],
          ['das Geld', 'pieniądze', 'Ich habe kein Geld.'],
          ['der Euro', 'euro', 'Das kostet zehn Euro.'],
          ['der Cent', 'cent', 'Fünfzig Cent Wechselgeld.'],
          ['billig', 'tani', 'Das ist sehr billig!'],
          ['teuer', 'drogi', 'Das ist zu teuer.'],
          ['das Angebot', 'oferta / promocja', 'Das ist ein gutes Angebot.'],
          ['die Rechnung', 'rachunek', 'Die Rechnung, bitte!'],
          ['die Quittung', 'paragon', 'Kann ich eine Quittung haben?'],
          ['bar', 'gotówką', 'Ich zahle bar.'],
          ['die Kreditkarte', 'karta kredytowa', 'Akzeptieren Sie Kreditkarten?'],
          ['Wie viel kostet das?', 'Ile to kosztuje?', 'Wie viel kostet das Buch?'],
          ['der Preis', 'cena', 'Der Preis ist fair.'],
          ['der Rabatt', 'rabat / zniżka', 'Gibt es einen Rabatt?'],
          ['einkaufen', 'robić zakupy', 'Ich gehe einkaufen.']
        ],
        grammar: {
          title: 'Modalny "möchten" (chciałbym) + Akkusativ',
          content: 'möchten (chciałbym): ich möchte • du möchtest • er/sie möchte\nwir möchten • ihr möchtet • sie möchten\n\nIch möchte einen Kaffee. (m→einen)\nIch möchte eine Quittung. (f→eine)\nIch möchte das Buch. (n→das)',
          note: 'W sklepie: Ich hätte gern... (bardziej grzecznie niż "ich möchte")'
        },
        tests: [
          {type:'de_pl', q:'die Quittung', a:'paragon'},
          {type:'de_pl', q:'einkaufen', a:'robić zakupy'},
          {type:'pl_de', q:'rabat', a:'der Rabatt'},
          {type:'pl_de', q:'płacić', a:'bezahlen'},
          {type:'fill', q:'Wie viel ___ das? (kosztuje)', a:'kostet'},
          {type:'fill', q:'Ich ___ bar. (płacę)', a:'zahle'},
          {type:'choice', q:'"Möchte" to forma dla:', a:'ich / er / sie',
           opts:['du','ich / er / sie','wir','ihr']},
          {type:'choice', q:'Akkusativ: "Ich möchte ___ Kaffee." (m)', a:'einen',
           opts:['ein','einen','dem','den']},
          {type:'pl_de', q:'gotówką', a:'bar'},
          {type:'de_pl', q:'das Angebot', a:'oferta / promocja'}
        ]
      },
      {
        id: 'A1_10', level: 'A1', num: 10,
        title: 'Pogoda i pory roku',
        intro: 'Poniedziałek. Rozmawiasz z Thomasem przy ekspresie do kawy — typowa berlińska pogoda.',
        dialogue: [
          {s: 'Thomas', de: 'Andrzej, wie findest du das Berliner Wetter?', pl: 'Andrzej, jak Ci się podoba berlińska pogoda?'},
          {s: 'Andrzej', de: 'Ehrlich gesagt — es regnet viel! In Polen ist es im Sommer wärmer.', pl: 'Szczerze mówiąc — dużo pada! W Polsce jest cieplej latem.'},
          {s: 'Thomas', de: 'Ha! Der Herbst ist hier wirklich grau. Im Winter schneit es auch viel.', pl: 'Ha! Jesień jest tu naprawdę szara. Zimą też dużo śniegu.'},
          {s: 'Andrzej', de: 'Gibt es hier gute Jahreszeiten?', pl: 'Czy są tu dobre pory roku?'},
          {s: 'Thomas', de: 'Der Frühling und der Sommer sind toll! Dann ist es warm und sonnig.', pl: 'Wiosna i lato są super! Wtedy jest ciepło i słonecznie.'},
          {s: 'Andrzej', de: 'Wie heiß wird es im Sommer?', pl: 'Jak gorąco jest latem?'},
          {s: 'Thomas', de: 'Manchmal dreißig Grad oder mehr. Aber meistens so zwanzig bis fünfundzwanzig.', pl: 'Czasem trzydzieści stopni lub więcej. Ale przeważnie tak dwadzieścia do dwudziestu pięciu.'}
        ],
        cultural: 'Pogoda to ulubiony temat small talk w Niemczech — podobnie jak w Polsce! "Schönes Wetter heute, oder?" to klasyczny starter rozmowy.',
        vocab: [
          ['das Wetter', 'pogoda', 'Wie ist das Wetter heute?'],
          ['die Sonne', 'słońce', 'Die Sonne scheint.'],
          ['der Regen', 'deszcz', 'Es regnet heute.'],
          ['der Schnee', 'śnieg', 'Im Winter gibt es Schnee.'],
          ['der Wind', 'wiatr', 'Es ist sehr windig heute.'],
          ['warm', 'ciepło', 'Es ist warm draußen.'],
          ['kalt', 'zimno', 'Im Winter ist es kalt.'],
          ['heiß', 'gorąco', 'Im Sommer ist es heiß.'],
          ['kühl', 'chłodno', 'Im Herbst ist es kühl.'],
          ['sonnig', 'słonecznie', 'Heute ist es sonnig.'],
          ['bewölkt', 'pochmurno', 'Es ist bewölkt.'],
          ['regnerisch', 'deszczowo', 'Das Wetter ist regnerisch.'],
          ['die Temperatur', 'temperatura', 'Die Temperatur beträgt 20 Grad.'],
          ['der Frühling', 'wiosna', 'Im Frühling blühen die Blumen.'],
          ['der Sommer', 'lato', 'Der Sommer ist meine Lieblingszeit.'],
          ['der Herbst', 'jesień', 'Im Herbst fallen die Blätter.'],
          ['der Winter', 'zima', 'Der Winter ist kalt.'],
          ['das Grad', 'stopień', 'Es sind 25 Grad.']
        ],
        grammar: {
          title: 'Konstrukcje bezosobowe: "es"',
          content: 'Es regnet. (Pada deszcz.) • Es schneit. (Śniega.) • Es ist kalt. (Jest zimno.)\nEs gibt... (Jest / Są...) → Es gibt Schnee im Winter.\n\nTemperatura: Es sind 20 Grad. / Es ist 20 Grad warm.',
          note: '"Es" w tych zdaniach jest formalnym podmiotem — tłumaczymy je kontekstowo, nie dosłownie.'
        },
        tests: [
          {type:'de_pl', q:'bewölkt', a:'pochmurno'},
          {type:'de_pl', q:'der Herbst', a:'jesień'},
          {type:'pl_de', q:'wiosna', a:'der Frühling'},
          {type:'pl_de', q:'gorąco', a:'heiß'},
          {type:'fill', q:'Es ___ heute. (regnen / pada)', a:'regnet'},
          {type:'fill', q:'Im Sommer ist es ___. (gorąco)', a:'heiß'},
          {type:'choice', q:'"Die Sonne scheint" znaczy:', a:'Słońce świeci',
           opts:['Pada deszcz','Słońce świeci','Jest pochmurno','Wieje wiatr']},
          {type:'choice', q:'Jak zapytamy o pogodę?', a:'Wie ist das Wetter?',
           opts:['Was ist das Wetter?','Wie ist das Wetter?','Wo ist das Wetter?','Wann ist das Wetter?']},
          {type:'pl_de', q:'temperatura', a:'die Temperatur'},
          {type:'de_pl', q:'windig', a:'wietrzny'}
        ]
      },
      {
        id: 'A1_11', level: 'A1', num: 11,
        title: 'Transport i kierunki',
        intro: 'Wtorek rano. Jedziesz do pracy metrem, ale zgubisz się. Pytasz przechodnia o drogę.',
        dialogue: [
          {s: 'Andrzej', de: 'Entschuldigung! Ich suche den Bahnhof Alexanderplatz. Wie komme ich dahin?', pl: 'Przepraszam! Szukam stacji Alexanderplatz. Jak tam dojść?'},
          {s: 'Passant', de: 'Gehen Sie geradeaus, dann links an der Ampel.', pl: 'Idź prosto, potem w lewo przy sygnalizacji.'},
          {s: 'Andrzej', de: 'Und nehme ich die U-Bahn oder die S-Bahn?', pl: 'I biorę U-Bahn czy S-Bahn?'},
          {s: 'Passant', de: 'Die U-Bahn Linie zwei fährt direkt zum Alex. Fährt alle fünf Minuten.', pl: 'Linia U2 jedzie bezpośrednio do Aleksa. Jeździ co pięć minut.'},
          {s: 'Andrzej', de: 'Wie weit ist es zu Fuß zur U-Bahn-Station?', pl: 'Jak daleko jest pieszo do stacji metra?'},
          {s: 'Passant', de: 'Ungefähr zehn Minuten. Sie sehen die Station auf der rechten Seite.', pl: 'Około dziesięciu minut. Zobaczy Pan stację po prawej stronie.'},
          {s: 'Andrzej', de: 'Vielen Dank! Das ist sehr hilfreich.', pl: 'Bardzo dziękuję! To bardzo pomocne.'}
        ],
        cultural: 'BVG (Berliner Verkehrsbetriebe) to system komunikacji w Berlinie — U-Bahn (metro), S-Bahn (szybka kolej miejska), Tram i Bus. Bilet ABC obejmuje całe miasto.',
        vocab: [
          ['das Auto', 'samochód', 'Ich fahre mit dem Auto.'],
          ['der Zug', 'pociąg', 'Der Zug fährt um 10 Uhr ab.'],
          ['der Bus', 'autobus', 'Ich nehme den Bus.'],
          ['die U-Bahn', 'metro', 'Die U-Bahn ist schnell.'],
          ['das Flugzeug', 'samolot', 'Wir fliegen nach Berlin.'],
          ['das Fahrrad', 'rower', 'Ich fahre Fahrrad.'],
          ['fahren', 'jechać', 'Ich fahre in die Arbeit.'],
          ['fliegen', 'latać', 'Wir fliegen morgen.'],
          ['der Bahnhof', 'dworzec', 'Der Bahnhof ist groß.'],
          ['der Flughafen', 'lotnisko', 'Der Flughafen ist weit.'],
          ['die Haltestelle', 'przystanek', 'Die Haltestelle ist hier.'],
          ['links', 'w lewo', 'Gehen Sie links.'],
          ['rechts', 'w prawo', 'Biegen Sie rechts ab.'],
          ['geradeaus', 'prosto', 'Gehen Sie geradeaus.'],
          ['die Straße', 'ulica', 'Die Hauptstraße ist dort.'],
          ['Wie komme ich zu...?', 'Jak dojdę do...?', 'Wie komme ich zum Bahnhof?'],
          ['weit / nah', 'daleko / blisko', 'Ist das weit von hier?'],
          ['die Minute', 'minuta', 'Fünf Minuten zu Fuß.']
        ],
        grammar: {
          title: 'Mit + Dativ (środek transportu) + Wegbeschreibung',
          content: 'Środek transportu: mit + Dativ\nmit dem Auto • mit dem Bus • mit der U-Bahn • mit dem Fahrrad\n\nOpis drogi:\nGehen Sie geradeaus! • Biegen Sie links/rechts ab! • Nehmen Sie die erste Straße links.',
          note: '"Zu Fuß gehen" = iść pieszo (nie używamy "mit"!)'
        },
        tests: [
          {type:'de_pl', q:'die Haltestelle', a:'przystanek'},
          {type:'de_pl', q:'geradeaus', a:'prosto'},
          {type:'pl_de', q:'lotnisko', a:'der Flughafen'},
          {type:'pl_de', q:'blisko', a:'nah'},
          {type:'fill', q:'Ich fahre ___ dem Auto. (z / mit)', a:'mit'},
          {type:'fill', q:'Biegen Sie ___ ab. (w prawo)', a:'rechts'},
          {type:'choice', q:'"Wie komme ich zum Bahnhof?" znaczy:', a:'Jak dojdę do dworca?',
           opts:['Gdzie jest dworzec?','Jak dojdę do dworca?','Kiedy jedzie pociąg?','Ile kosztuje bilet?']},
          {type:'choice', q:'Metro + mit → ?', a:'mit der U-Bahn',
           opts:['mit dem U-Bahn','mit der U-Bahn','mit das U-Bahn','mit die U-Bahn']},
          {type:'pl_de', q:'rower', a:'das Fahrrad'},
          {type:'de_pl', q:'der Bahnhof', a:'dworzec'}
        ]
      },
      {
        id: 'A1_12', level: 'A1', num: 12,
        title: 'Powtórzenie A1 — Egzamin końcowy',
        intro: 'Minął pierwszy miesiąc w Berlinie. Spotykasz Clarę Schmidt na korytarzu — rozmawiasz swobodnie po niemiecku o swoich postępach.',
        dialogue: [
          {s: 'Clara', de: 'Andrzej! Ein Monat schon! Wie läuft es?', pl: 'Andrzej! Już miesiąc! Jak leci?'},
          {s: 'Andrzej', de: 'Sehr gut! Ich spreche jeden Tag Deutsch. Es macht mir Spaß!', pl: 'Bardzo dobrze! Mówię po niemiecku każdego dnia. To sprawia mi radość!'},
          {s: 'Clara', de: 'Toll! Dein Deutsch ist schon viel besser als am Anfang.', pl: 'Super! Twój niemiecki jest już znacznie lepszy niż na początku.'},
          {s: 'Andrzej', de: 'Danke! Ich lerne auch neue Wörter — zum Beispiel Bahnhof, Wetter, Familie...', pl: 'Dziękuję! Uczę się też nowych słów — na przykład dworzec, pogoda, rodzina...'},
          {s: 'Clara', de: 'Perfekt! Willst du mit uns heute Abend etwas trinken?', pl: 'Idealnie! Chcesz dziś wieczór z nami coś wypić?'},
          {s: 'Andrzej', de: 'Ja, sehr gerne! Um wie viel Uhr und wo?', pl: 'Tak, bardzo chętnie! O której i gdzie?'}
        ],
        cultural: 'Egzamin A1 Goethe-Institut lub telc A1 potwierdza podstawową znajomość języka. Wielu pracodawców w Niemczech wymaga minimum A2-B1 nawet na stanowiskach IT.',
        vocab: [],
        grammar: {
          title: 'Powtórzenie wszystkich zagadnień A1',
          content: '1. Powitania i przedstawianie się (sein, heißen, kommen)\n2. Liczby i ceny (wie viel kostet)\n3. Kolory i przymiotniki orzecznikowe\n4. Rodzina (mein/meine, rodzajniki)\n5. Jedzenie (essen, trinken, mögen)\n6. Czas (am/um/im, halb/Viertel)\n7. Dom i meble (in/auf/an + Dativ)\n8. Praca i zawody (sein + zawód bez rodzajnika)\n9. Zakupy (möchten + Akkusativ)\n10. Pogoda (es regnet/schneit)\n11. Transport (mit + Dativ, kierunki)',
          note: 'Egzamin składa się z 20 pytań obejmujących cały poziom A1. Próg zaliczenia: 75%.'
        },
        tests: [
          {type:'pl_de', q:'Dzień dobry (rano)', a:'Guten Morgen'},
          {type:'de_pl', q:'die Geschwister', a:'rodzeństwo'},
          {type:'pl_de', q:'pyszny', a:'lecker'},
          {type:'de_pl', q:'Mittwoch', a:'środa'},
          {type:'pl_de', q:'sypialnia', a:'das Schlafzimmer'},
          {type:'fill', q:'Ich ___ Programmierer. (sein)', a:'bin'},
          {type:'fill', q:'Es ___ heute. (regnen)', a:'regnet'},
          {type:'choice', q:'"Halb zehn" to godzina:', a:'9:30',
           opts:['10:30','9:30','10:15','9:15']},
          {type:'choice', q:'Środek transportu: mit + ?', a:'Dativ',
           opts:['Nominativ','Akkusativ','Dativ','Genitiv']},
          {type:'pl_de', q:'paragon', a:'die Quittung'},
          {type:'de_pl', q:'bewölkt', a:'pochmurno'},
          {type:'pl_de', q:'lotnisko', a:'der Flughafen'},
          {type:'fill', q:'Ich fahre ___ dem Bus. (mit)', a:'mit'},
          {type:'fill', q:'___ Montag arbeite ich. (am/w)', a:'Am'},
          {type:'choice', q:'Zawód po "sein": Ich bin ___', a:'Arzt',
           opts:['ein Arzt','der Arzt','Arzt','einem Arzt']},
          {type:'de_pl', q:'das Gehalt', a:'wynagrodzenie'},
          {type:'pl_de', q:'tani', a:'billig'},
          {type:'choice', q:'Forma grzecznościowa "ty" to:', a:'Sie',
           opts:['du','ihr','Sie','er']},
          {type:'de_pl', q:'geradeaus', a:'prosto'},
          {type:'pl_de', q:'Jak się masz?', a:'Wie geht\'s?'}
        ]
      }
    ]
  },

  A2: {
    name: 'A2 — Grundlegende Kenntnisse',
    namePl: 'A2 — Poziom podstawowy',
    desc: 'Codzienne czynności, zdrowie, podróże, opinie, Perfekt i Präteritum',
    lessonsTotal: 16,
    lessons: [
      { id:'A2_01', level:'A2', num:1, title:'Codzienne czynności i rutyna',
        vocab:[
          ['aufstehen','wstawać','Ich stehe um 7 Uhr auf.'],
          ['sich waschen','myć się','Ich wasche mich morgens.'],
          ['frühstücken','jeść śniadanie','Wir frühstücken zusammen.'],
          ['zur Arbeit fahren','jechać do pracy','Ich fahre mit dem Zug zur Arbeit.'],
          ['die Pause','przerwa','Wir machen eine Pause.'],
          ['nach Hause kommen','wracać do domu','Ich komme um 18 Uhr nach Hause.'],
          ['abendessen','jeść kolację','Wir essen um 19 Uhr zu Abend.'],
          ['fernsehen','oglądać telewizję','Abends sehe ich fern.'],
          ['schlafen gehen','iść spać','Ich gehe um 23 Uhr schlafen.'],
          ['sich treffen','spotykać się','Wir treffen uns am Wochenende.'],
          ['einkaufen gehen','iść na zakupy','Samstags gehe ich einkaufen.'],
          ['Sport treiben','uprawiać sport','Ich treibe dreimal pro Woche Sport.'],
          ['lesen','czytać','Ich lese gern Bücher.'],
          ['aufräumen','sprzątać','Sonntags räume ich auf.'],
          ['der Wecker','budzik','Mein Wecker klingelt um 6 Uhr.'],
          ['gewöhnlich / normalerweise','zwykle','Normalerweise esse ich um 12 Uhr.'],
          ['manchmal','czasami','Manchmal gehe ich joggen.'],
          ['immer','zawsze','Ich trinke immer Kaffee morgens.']
        ],
        grammar:{title:'Czasowniki rozdzielnie złożone',content:'aufstehen → ich stehe...auf (auf- na końcu!)\nfernzusehen → ich sehe...fern\naufzuräumen → ich räume...auf\n\nW zdaniu głównym: Ich stehe um 7 Uhr auf.\nPo modalnym: Ich muss um 7 Uhr aufstehen.',note:'W bezokoliczniku: aufstehen (razem). W zdaniu: auf hinten (na końcu)!'},
        tests:[
          {type:'de_pl',q:'aufstehen',a:'wstawać'},
          {type:'pl_de',q:'oglądać telewizję',a:'fernsehen'},
          {type:'fill',q:'Ich stehe um 7 Uhr ___. (aufstehen)',a:'auf'},
          {type:'choice',q:'Czasownik rozdzielnie złożony w zdaniu:',a:'Ich räume auf.',
           opts:['Ich aufräume.','Ich räume auf.','Ich räumeauf.','Aufräume ich.']},
          {type:'de_pl',q:'der Wecker',a:'budzik'},
          {type:'pl_de',q:'zawsze',a:'immer'},
          {type:'fill',q:'Ich ___ um 23 Uhr schlafen. (gehen)',a:'gehe'},
          {type:'de_pl',q:'manchmal',a:'czasami'},
          {type:'pl_de',q:'przerwa',a:'die Pause'},
          {type:'choice',q:'"Normalerweise" znaczy:',a:'zwykle',
           opts:['nigdy','zawsze','zwykle','rzadko']}
        ]
      },
      { id:'A2_02', level:'A2', num:2, title:'Zdrowie i ciało',
        vocab:[
          ['der Kopf','głowa','Ich habe Kopfschmerzen.'],
          ['der Bauch','brzuch','Mir tut der Bauch weh.'],
          ['der Rücken','plecy','Rückenschmerzen sind häufig.'],
          ['die Hand','ręka','Ich habe mir die Hand verletzt.'],
          ['das Bein','noga','Sein Bein ist gebrochen.'],
          ['krank','chory','Ich bin krank.'],
          ['gesund','zdrowy','Ich bin wieder gesund.'],
          ['der Arzttermin','wizyta u lekarza','Ich habe einen Arzttermin.'],
          ['die Apotheke','apteka','Ich gehe in die Apotheke.'],
          ['das Medikament','lek / lekarstwo','Der Arzt gibt mir ein Medikament.'],
          ['Schmerzen haben','mieć ból','Ich habe Schmerzen.'],
          ['Fieber haben','mieć gorączkę','Das Kind hat Fieber.'],
          ['sich erholen','odpoczywać / dochodzić do siebie','Ich erhole mich.'],
          ['der Hustel','kaszel','Ich habe Husten.'],
          ['die Erkältung','przeziębienie','Ich habe eine Erkältung.'],
          ['die Krankenversicherung','ubezpieczenie zdrowotne','Ich habe eine Krankenversicherung.'],
          ['verschreiben','przepisywać (receptę)','Der Arzt verschreibt mir Tabletten.'],
          ['weh tun','boleć','Mir tut der Kopf weh.']
        ],
        grammar:{title:'Dativ z "mir / dir / ihm" — "weh tun"',content:'Mir tut der Kopf weh. (Boli mnie głowa.)\nDir tut der Rücken weh.\nIhm / ihr tut der Bauch weh.\n\nzaimki Dativ: mir • dir • ihm • ihr • uns • euch • ihnen',note:'"Weh tun" dosłownie: "głowa robi mi ból" — podmiotem jest CZĘŚĆ CIAŁA, nie osoba!'},
        tests:[
          {type:'de_pl',q:'die Apotheke',a:'apteka'},
          {type:'pl_de',q:'przeziębienie',a:'die Erkältung'},
          {type:'fill',q:'Mir tut der Kopf ___. (weh tun)',a:'weh'},
          {type:'choice',q:'"Fieber haben" to:',a:'mieć gorączkę',
           opts:['mieć kaszel','mieć ból','mieć gorączkę','być zdrowym']},
          {type:'de_pl',q:'verschreiben',a:'przepisywać (receptę)'},
          {type:'pl_de',q:'chory',a:'krank'},
          {type:'fill',q:'___ tut der Rücken weh. (mnie)',a:'Mir'},
          {type:'de_pl',q:'sich erholen',a:'odpoczywać / dochodzić do siebie'},
          {type:'pl_de',q:'ubezpieczenie zdrowotne',a:'die Krankenversicherung'},
          {type:'choice',q:'Dativ "ich" to:',a:'mir',opts:['mich','mir','mein','ich']}
        ]
      },
      { id:'A2_03', level:'A2', num:3, title:'Ubrania i opis wyglądu', vocab:[
        ['das Hemd','koszula','Er trägt ein weißes Hemd.'],['die Hose','spodnie','Eine schwarze Hose.'],
        ['das Kleid','sukienka','Sie trägt ein rotes Kleid.'],['der Mantel','płaszcz','Im Winter brauche ich einen Mantel.'],
        ['die Jacke','kurtka/marynarka','Ich ziehe die Jacke an.'],['der Schuh','but','Diese Schuhe sind bequem.'],
        ['tragen','nosić/ubierać','Was trägst du heute?'],['anziehen','zakładać (ubranie)','Ich ziehe mich an.'],
        ['ausziehen','zdejmować','Er zieht den Mantel aus.'],['groß/klein','wysoki/niski','Er ist groß.'],
        ['schlank','szczupły','Sie ist schlank.'],['die Haare','włosy','Sie hat lange Haare.'],
        ['blond/braun','blond/brązowy','Er hat blonde Haare.'],['die Brille','okulary','Er trägt eine Brille.'],
        ['passen','pasować','Das Hemd passt mir gut.'],['die Größe','rozmiar','Welche Größe haben Sie?'],
        ['die Mode','moda','Mode interessiert mich.'],['bequem','wygodny','Diese Schuhe sind bequem.']
      ], grammar:{title:'Koniugacja "tragen" + przymiotniki atrybutywne',
        content:'tragen: ich trage • du trägst • er/sie trägt • wir tragen\n\nPrzym. atrybutywne (nieokreślone):\nein schwarzer Mantel (m) • eine rote Jacke (f) • ein weißes Hemd (n)',
        note:'Po "einen/eine/ein" końcówki: -en (m) • -e (f) • -es (n). To tzw. gemischte Deklination.'
      }, tests:[
        {type:'de_pl',q:'die Jacke',a:'kurtka/marynarka'},{type:'pl_de',q:'sukienka',a:'das Kleid'},
        {type:'fill',q:'Er ___ ein weißes Hemd. (tragen)',a:'trägt'},
        {type:'choice',q:'"Welche Größe haben Sie?" pyta o:',a:'rozmiar',opts:['kolor','rozmiar','cenę','materiał']},
        {type:'de_pl',q:'passen',a:'pasować'},{type:'pl_de',q:'wygodny',a:'bequem'},
        {type:'fill',q:'Ich ziehe den Mantel ___. (ausziehen)',a:'aus'},
        {type:'de_pl',q:'schlank',a:'szczupły'},{type:'pl_de',q:'okulary',a:'die Brille'},
        {type:'choice',q:'"Ein schwarzer Mantel" — końcówka "-er" bo:',a:'Männlich (m) po "ein"',
         opts:['Żeński po "ein"','Männlich (m) po "ein"','Nijaki po "ein"','Plural']}
      ]},
      { id:'A2_04', level:'A2', num:4, title:'Uczucia i emocje', vocab:[
        ['sich freuen','cieszyć się','Ich freue mich auf das Wochenende.'],
        ['traurig','smutny','Ich bin traurig.'],['wütend','wściekły','Er ist wütend.'],
        ['aufgeregt','podekscytowany','Ich bin aufgeregt.'],['nervös','zdenerwowany','Ich bin nervös.'],
        ['zufrieden','zadowolony','Ich bin zufrieden.'],['enttäuscht','rozczarowany','Ich bin enttäuscht.'],
        ['sich ärgern','denerwować się','Ich ärgere mich.'],
        ['sich Sorgen machen','martwić się','Ich mache mir Sorgen.'],
        ['lachen','śmiać się','Wir lachen viel.'],['weinen','płakać','Das Kind weint.'],
        ['hoffen','mieć nadzieję','Ich hoffe, dass es klappt.'],
        ['fürchten','bać się','Ich fürchte mich.'],['lieben','kochać','Ich liebe meine Familie.'],
        ['hassen','nienawidzić','Ich hasse Montage.'],
        ['sich wohlfühlen','czuć się dobrze','Ich fühle mich wohl.'],
        ['der Stress','stres','Ich habe viel Stress.'],['entspannen','relaksować się','Ich entspanne mich.']
      ], grammar:{title:'Czasowniki zwrotne (Reflexivverben)',
        content:'sich freuen: ich freue mich • du freust dich • er/sie freut sich • wir freuen uns\nsich ärgern: ich ärgere mich • er ärgert sich\n\nReflexivpronomen Akkusativ: mich • dich • sich • uns • euch • sich',
        note:'Niektóre są zwrotne tylko po niemiecku: sich freuen = cieszyć się (bez "się" w ang./pl. byłoby "to be happy")'
      }, tests:[
        {type:'de_pl',q:'zufrieden',a:'zadowolony'},{type:'pl_de',q:'rozczarowany',a:'enttäuscht'},
        {type:'fill',q:'Ich freue ___ auf das Wochenende.',a:'mich'},
        {type:'choice',q:'"Sich ärgern" dla "er" to:',a:'Er ärgert sich.',
         opts:['Er ärgert mich.','Er ärgert sich.','Er sich ärgert.','Er ärgert dich.']},
        {type:'de_pl',q:'aufgeregt',a:'podekscytowany'},{type:'pl_de',q:'relaksować się',a:'sich entspannen'},
        {type:'fill',q:'Er ist ___. (wściekły)',a:'wütend'},
        {type:'de_pl',q:'sich Sorgen machen',a:'martwić się'},
        {type:'pl_de',q:'mieć nadzieję',a:'hoffen'},
        {type:'choice',q:'Reflexivpronomen dla "wir" to:',a:'uns',opts:['mich','sich','uns','euch']}
      ]},
      { id:'A2_05', level:'A2', num:5, title:'Restauracja i jedzenie na mieście', vocab:[
        ['das Restaurant','restauracja','Wir essen im Restaurant.'],
        ['die Speisekarte','menu/karta','Die Speisekarte, bitte!'],
        ['bestellen','zamawiać','Ich möchte bestellen.'],['die Vorspeise','przystawka','Als Vorspeise nehme ich Suppe.'],
        ['das Hauptgericht','danie główne','Was nehmen Sie als Hauptgericht?'],
        ['die Nachspeise','deser','Zum Dessert nehme ich Eis.'],
        ['der Kellner/die Kellnerin','kelner/kelnerka','Der Kellner kommt.'],
        ['empfehlen','polecać','Was können Sie empfehlen?'],['vegetarisch','wegetariański','Ich esse vegetarisch.'],
        ['die Allergie','alergia','Ich habe eine Allergie gegen Nüsse.'],
        ['das Trinkgeld','napiwek','Ich gebe Trinkgeld.'],['die Reservierung','rezerwacja','Ich habe eine Reservierung.'],
        ['Stimmt so!','Reszty nie trzeba!','Stimmt so, danke!'],
        ['zum Mitnehmen','na wynos','Einmal zum Mitnehmen, bitte.'],
        ['scharf','ostry','Das Essen ist zu scharf.'],['mild','łagodny','Ich mag mildes Essen.'],
        ['die Portion','porcja','Eine große Portion, bitte.'],['schmecken','smakować','Das schmeckt sehr gut!']
      ], grammar:{title:'Konjunktiv II — grzeczne prośby (möchte / würde / hätte)',
        content:'möchte (chciałbym): Ich möchte einen Tisch reservieren.\nhätte gern (chciałbym mieć): Ich hätte gern die Suppe.\nwürde + inf (chciałbym zrobić): Ich würde gern zahlen.\n\nto grzeczniejsze od Imperativu!',
        note:'"Einmal" = jedna porcja/jedno zamówienie (dosłownie "raz")'
      }, tests:[
        {type:'de_pl',q:'die Speisekarte',a:'menu/karta'},{type:'pl_de',q:'napiwek',a:'das Trinkgeld'},
        {type:'fill',q:'Was ___ Sie empfehlen? (können)',a:'können'},
        {type:'choice',q:'"Stimmt so!" w restauracji znaczy:',a:'Reszty nie trzeba',
         opts:['Proszę o rachunek','To jest za drogie','Reszty nie trzeba','Chciałbym zamówić']},
        {type:'de_pl',q:'scharf',a:'ostry'},{type:'pl_de',q:'wegetariański',a:'vegetarisch'},
        {type:'fill',q:'Zum ___ nehme ich Eis. (Dessert/deser)',a:'Dessert'},
        {type:'de_pl',q:'empfehlen',a:'polecać'},{type:'pl_de',q:'porcja',a:'die Portion'},
        {type:'choice',q:'Grzeczna prośba "chciałbym zapłacić":',a:'Ich würde gern zahlen.',
         opts:['Ich zahle!','Zahlen!','Ich würde gern zahlen.','Gib mir die Rechnung!']}
      ]},
      { id:'A2_06', level:'A2', num:6, title:'Czas przeszły — Perfekt', vocab:[
        ['haben + Partizip II','czas przeszły (Perfekt)','Ich habe gegessen.'],
        ['sein + Partizip II','Perfekt z "sein"','Ich bin gefahren.'],
        ['gegessen','(z)jeść — Partizip II','Ich habe Pizza gegessen.'],
        ['getrunken','(wy)pić — Partizip II','Ich habe Wasser getrunken.'],
        ['gekauft','kupić — Partizip II','Ich habe ein Buch gekauft.'],
        ['gemacht','zrobić — Partizip II','Was hast du gemacht?'],
        ['gesehen','zobaczyć — Partizip II','Ich habe einen Film gesehen.'],
        ['gehört','słyszeć — Partizip II','Ich habe Musik gehört.'],
        ['gearbeitet','pracować — Partizip II','Er hat gearbeitet.'],
        ['gefahren','jechać — Partizip II (sein)','Ich bin nach Berlin gefahren.'],
        ['gegangen','iść — Partizip II (sein)','Wir sind ins Kino gegangen.'],
        ['gekommen','przyjść — Partizip II (sein)','Er ist spät gekommen.'],
        ['gewesen','być — Partizip II (sein)','Ich bin krank gewesen.'],
        ['geschrieben','pisać — Partizip II','Ich habe eine E-Mail geschrieben.'],
        ['gesprochen','mówić — Partizip II','Wir haben Deutsch gesprochen.'],
        ['ge-...-t','słabe formy (regularne)','kaufen → gekauft'],
        ['ge-...-en','mocne formy (nieregularne)','fahren → gefahren'],
        ['Wann? / Wie lange?','Kiedy? / Jak długo?','Wann bist du gefahren?']
      ], grammar:{title:'Perfekt: haben/sein + Partizip II',
        content:'HABEN: czynności bez ruchu lub zmiany miejsca\nIch habe gegessen/getrunken/gekauft/gesehen/gemacht\n\nSEIN: ruch, zmiana miejsca/stanu + sein/bleiben/werden\nIch bin gefahren/gegangen/gekommen/geflogen/geblieben\n\nPartizip II: ge- + Stamm + -t (reg.) lub ge- + Stamm + -en (nieregularne)',
        note:'Trennbare Verben: auf|stehen → aufgestanden (ge- W ŚRODKU!): aufge|standen'
      }, tests:[
        {type:'pl_de',q:'kupić (Partizip II)',a:'gekauft'},
        {type:'pl_de',q:'pojechać (Partizip II)',a:'gefahren'},
        {type:'fill',q:'Ich ___ einen Film gesehen. (haben)',a:'habe'},
        {type:'fill',q:'Wir ___ ins Kino gegangen. (sein)',a:'sind'},
        {type:'choice',q:'"Gegessen" jest Partizip II od:',a:'essen',
         opts:['gehen','essen','geben','sehen']},
        {type:'choice',q:'Który czasownik tworzy Perfekt z "sein"?',a:'fahren',
         opts:['kaufen','essen','fahren','schreiben']},
        {type:'de_pl',q:'geschrieben',a:'pisać — Partizip II'},
        {type:'fill',q:'Er ___ spät ___. (kommen — Perfekt)',a:'ist / gekommen'},
        {type:'pl_de',q:'rozmawiać — Partizip II',a:'gesprochen'},
        {type:'de_pl',q:'gewesen',a:'być — Partizip II (sein)'}
      ]},
      { id:'A2_07', level:'A2', num:7, title:'Podróże i wakacje', vocab:[
        ['die Reise','podróż','Ich mache eine Reise nach Deutschland.'],
        ['buchen','rezerwować','Ich habe das Hotel gebucht.'],
        ['der Koffer','walizka','Ich packe meinen Koffer.'],
        ['einchecken','zameldować się','Ich checke um 14 Uhr ein.'],
        ['das Hotel','hotel','Wir wohnen im Hotel.'],
        ['die Unterkunft','zakwaterowanie','Wo ist die Unterkunft?'],
        ['die Sehenswürdigkeit','atrakcja turystyczna','Welche Sehenswürdigkeiten gibt es?'],
        ['das Museum','muzeum','Wir besuchen ein Museum.'],
        ['die Landschaft','krajobraz','Die Landschaft ist wunderschön.'],
        ['der Strand','plaża','Am Strand ist es schön.'],
        ['das Ausland','zagranica','Ich fahre ins Ausland.'],
        ['der Urlaub','urlop/wakacje','Ich bin im Urlaub.'],
        ['Spaß haben','bawić się dobrze','Wir haben viel Spaß.'],
        ['die Postkarte','pocztówka','Ich schreibe eine Postkarte.'],
        ['verloren gehen','zgubić się','Ich habe mich verlaufen.'],
        ['die Reiseversicherung','ubezpieczenie podróżne','Ich habe eine Reiseversicherung.'],
        ['empfehlen','polecać','Können Sie ein Restaurant empfehlen?'],
        ['wandern','wędrować/chodzić po górach','Wir gehen wandern.']
      ], grammar:{title:'Präteritum czasowników "haben" i "sein"',
        content:'haben (Präteritum): ich hatte • du hattest • er/sie hatte • wir hatten • ihr hattet • sie hatten\n\nsein (Präteritum): ich war • du warst • er/sie war • wir waren • ihr wart • sie waren\n\nW mowie: używamy głównie Perfekt. Hatte/war — w narracji i piśmie.',
        note:'Wyjątek: "hatte" i "war" używamy nawet w mowie potocznej (nie "habe gehabt" i "bin gewesen")'
      }, tests:[
        {type:'de_pl',q:'die Sehenswürdigkeit',a:'atrakcja turystyczna'},
        {type:'pl_de',q:'walizka',a:'der Koffer'},
        {type:'fill',q:'Ich ___ das Hotel gebucht. (Perfekt)',a:'habe'},
        {type:'fill',q:'Gestern ___ ich im Urlaub. (sein — Prät.)',a:'war'},
        {type:'choice',q:'"Hatte" to Präteritum od:',a:'haben',opts:['sein','werden','haben','gehen']},
        {type:'de_pl',q:'wandern',a:'wędrować/chodzić po górach'},
        {type:'pl_de',q:'zakwaterowanie',a:'die Unterkunft'},
        {type:'fill',q:'Ich ___ viel Spaß. (haben — Prät.)',a:'hatte'},
        {type:'de_pl',q:'das Ausland',a:'zagranica'},
        {type:'choice',q:'"Waren" to Präteritum od:',a:'sein',opts:['werden','sein','haben','fahren']}
      ]},
      { id:'A2_08', level:'A2', num:8, title:'Hobby i czas wolny', vocab:[
        ['das Hobby','hobby','Was sind deine Hobbys?'],['lesen','czytać','Ich lese gern.'],
        ['Musik hören','słuchać muzyki','Ich höre Musik.'],
        ['ins Kino gehen','iść do kina','Wir gehen ins Kino.'],
        ['Sport machen','uprawiać sport','Ich mache gern Sport.'],
        ['schwimmen','pływać','Im Sommer schwimme ich.'],
        ['kochen','gotować','Ich koche als Hobby.'],
        ['zeichnen','rysować','Sie zeichnet sehr gut.'],
        ['fotografieren','fotografować','Er fotografiert gern.'],
        ['reisen','podróżować','Reisen ist mein Hobby.'],
        ['spielen','grać / bawić się','Ich spiele Gitarre.'],
        ['das Konzert','koncert','Ich gehe zum Konzert.'],
        ['der Verein','klub / stowarzyszenie','Ich bin in einem Verein.'],
        ['sich entspannen','relaksować się','Ich entspanne mich.'],
        ['das Wochenende','weekend','Am Wochenende schlafe ich lange.'],
        ['free time','czas wolny — patrz Freizeit','In meiner Freizeit lese ich.'],
        ['die Freizeit','czas wolny','Was machst du in deiner Freizeit?'],
        ['begeistert von','zachwycony / pasjonat','Ich bin begeistert von Musik.']
      ], grammar:{title:'Zdania z "weil" i "dass"',
        content:'weil (bo/ponieważ): czasownik NA KOŃCU!\nIch lese gern, weil es entspannend ist.\n\ndass (że): czasownik NA KOŃCU!\nIch denke, dass Lesen gut ist.\n\nWICHTIG: po spójnikach podrzędnych (weil, dass, wenn, ob...) → czasownik na końcu!',
        note:'"Denn" też znaczy "bo" — ale bez przestawienia szyku! (zdanie współrzędne)'
      }, tests:[
        {type:'de_pl',q:'die Freizeit',a:'czas wolny'},
        {type:'pl_de',q:'fotografować',a:'fotografieren'},
        {type:'fill',q:'Ich lese gern, weil es entspannend ___. (sein)',a:'ist'},
        {type:'choice',q:'Po "weil" czasownik idzie:',a:'na koniec zdania',
         opts:['na początek','na koniec zdania','na drugie miejsce','gdziekolwiek']},
        {type:'de_pl',q:'der Verein',a:'klub / stowarzyszenie'},
        {type:'pl_de',q:'koncert',a:'das Konzert'},
        {type:'fill',q:'Ich denke, ___ Reisen gut ist.',a:'dass'},
        {type:'de_pl',q:'begeistert von',a:'zachwycony / pasjonat'},
        {type:'pl_de',q:'rysować',a:'zeichnen'},
        {type:'choice',q:'"Denn" a "weil" — różnica:',a:'"Denn" — normalny szyk; "weil" — czasownik na końcu',
         opts:['"Denn" jest bardziej formalny','"Denn" — normalny szyk; "weil" — czasownik na końcu',
               'Są identyczne','Używamy tylko "weil"']}
      ]},
      { id:'A2_09', level:'A2', num:9, title:'Szkoła, edukacja i język', vocab:[
        ['die Schule','szkoła','Ich gehe in die Schule.'],
        ['die Universität','uniwersytet','Ich studiere an der Universität.'],
        ['das Studium','studia','Mein Studium dauert 3 Jahre.'],
        ['der Kurs','kurs','Ich mache einen Deutschkurs.'],
        ['lernen','uczyć się','Ich lerne Deutsch.'],
        ['studieren','studiować','Er studiert Informatik.'],
        ['die Prüfung','egzamin','Ich habe morgen eine Prüfung.'],
        ['bestehen','zdać (egzamin)','Ich habe die Prüfung bestanden.'],
        ['durchfallen','oblać (egzamin)','Er ist durchgefallen.'],
        ['das Zeugnis','świadectwo','Ich habe gute Noten.'],
        ['die Note','ocena','Eine gute Note bekommen.'],
        ['der Abschluss','dyplom/ukończenie','Ich habe einen Bachelor-Abschluss.'],
        ['die Hausaufgaben','praca domowa','Ich mache meine Hausaufgaben.'],
        ['erklären','wyjaśniać','Kannst du das erklären?'],
        ['verstehen','rozumieć','Ich verstehe das nicht.'],
        ['wiederholen','powtarzać','Wir wiederholen den Stoff.'],
        ['das Wörterbuch','słownik','Ich benutze ein Wörterbuch.'],
        ['fließend','płynnie','Ich spreche fließend Englisch.']
      ], grammar:{title:'Modalverben w czasie przeszłym (Präteritum)',
        content:'müssen: ich musste • du musstest • er musste\nkönnen: ich konnte • du konntest • er konnte\nwollen: ich wollte • du wolltest • er wollte\ndürfen: ich durfte • sollen: ich sollte\n\nIch musste die Prüfung wiederholen.',
        note:'Modalne w Präteritum (nie Perfekt!) — "Ich habe gemusst" też istnieje, ale rzadko.'
      }, tests:[
        {type:'de_pl',q:'die Prüfung',a:'egzamin'},
        {type:'pl_de',q:'zdać egzamin',a:'die Prüfung bestehen'},
        {type:'fill',q:'Ich ___ die Prüfung bestanden. (haben — Perf.)',a:'habe'},
        {type:'fill',q:'Er ___ die Hausaufgaben machen. (müssen — Prät.)',a:'musste'},
        {type:'choice',q:'"Fließend" znaczy:',a:'płynnie',opts:['szybko','płynnie','dobrze','poprawnie']},
        {type:'de_pl',q:'das Wörterbuch',a:'słownik'},
        {type:'pl_de',q:'oblać egzamin',a:'durchfallen'},
        {type:'fill',q:'Ich ___ das nicht verstehen. (können — Prät.)',a:'konnte'},
        {type:'de_pl',q:'das Zeugnis',a:'świadectwo'},
        {type:'choice',q:'Präteritum "wollen" dla "ich":',a:'wollte',
         opts:['wollte','wollte','wunschte','willte']}
      ]},
      { id:'A2_10', level:'A2', num:10, title:'Technologia i praca biurowa', vocab:[
        ['das Handy','telefon komórkowy','Mein Handy ist neu.'],
        ['der Computer','komputer','Ich arbeite am Computer.'],
        ['die E-Mail','email','Ich schreibe eine E-Mail.'],
        ['das Meeting','spotkanie','Wir haben ein Meeting um 10 Uhr.'],
        ['die Präsentation','prezentacja','Ich halte eine Präsentation.'],
        ['das Dokument','dokument','Schicken Sie mir das Dokument.'],
        ['speichern','zapisywać','Ich speichere die Datei.'],
        ['herunterladen','pobierać','Ich lade die Datei herunter.'],
        ['die Datei','plik','Kannst du die Datei schicken?'],
        ['das Passwort','hasło','Ich habe mein Passwort vergessen.'],
        ['der Termin','spotkanie/termin','Ich habe einen Termin.'],
        ['die Videokonferenz','wideokonferencja','Wir machen eine Videokonferenz.'],
        ['planen','planować','Ich plane das Projekt.'],
        ['die Aufgabe','zadanie','Ich habe viele Aufgaben.'],
        ['die Frist','termin (deadline)','Die Frist ist Freitag.'],
        ['erledigen','załatwiać','Ich erledige die Aufgaben.'],
        ['schicken','wysyłać','Schick mir die Datei!'],
        ['der Anhang','załącznik','Ich schicke die Datei als Anhang.']
      ], grammar:{title:'Tryb rozkazujący (Imperativ)',
        content:'du: Schick! • Komm! • Arbeite! (Stamm, bez -st)\nihr: Schickt! • Kommt! • Arbeitet!\nSie: Schicken Sie! • Kommen Sie! (z "Sie")\n\nSpecjalnie: sein → Sei! (du) • Seid! (ihr) • Seien Sie! (Sie)',
        note:'"Bitte" zmiękicza rozkaz: Schick mir bitte die Datei! = poproszę o wysłanie pliku'
      }, tests:[
        {type:'de_pl',q:'die Frist',a:'termin (deadline)'},
        {type:'pl_de',q:'wideokonferencja',a:'die Videokonferenz'},
        {type:'fill',q:'___ mir die Datei! (schicken — Imperativ du)',a:'Schick'},
        {type:'choice',q:'Imperativ "Sie" od "kommen":',a:'Kommen Sie!',
         opts:['Kommen!','Komm Sie!','Kommen Sie!','Sie kommen!']},
        {type:'de_pl',q:'erledigen',a:'załatwiać'},
        {type:'pl_de',q:'zapisywać (plik)',a:'speichern'},
        {type:'fill',q:'Ich ___ die Datei herunter. (herunterladen)',a:'lade'},
        {type:'de_pl',q:'der Anhang',a:'załącznik'},
        {type:'pl_de',q:'planować',a:'planen'},
        {type:'choice',q:'"Bitte" w zdaniu rozkazującym:',a:'Zmiękicza rozkaz, grzeczniej',
         opts:['Zmienia znaczenie','Jest obowiązkowe','Zmiękicza rozkaz, grzeczniej','Nic nie zmienia']}
      ]},
      { id:'A2_11', level:'A2', num:11, title:'Opis miasta i środowisko', vocab:[
        ['die Stadt','miasto','Ich wohne in einer großen Stadt.'],
        ['das Zentrum','centrum','Das Zentrum ist belebte.'],
        ['der Park','park','Im Park ist es schön.'],
        ['das Rathaus','ratusz','Das Rathaus ist alt.'],
        ['die Kirche','kościół','Die Kirche ist sehr schön.'],
        ['das Einkaufszentrum','centrum handlowe','Ich gehe ins Einkaufszentrum.'],
        ['das Umwelt','środowisko','Wir müssen die Umwelt schützen.'],
        ['recyclen','recyklingować','Wir recyclen Papier.'],
        ['der Müll','śmieci','Ich trenne den Müll.'],
        ['die Energie','energia','Wir sparen Energie.'],
        ['das Fahrrad','rower','Ich fahre Fahrrad statt Auto.'],
        ['öffentliche Verkehrsmittel','komunikacja publiczna','Ich nehme öffentliche Verkehrsmittel.'],
        ['der Lärm','hałas','Der Lärm ist störend.'],
        ['die Luft','powietrze','Die Luft ist frisch.'],
        ['schützen','chronić','Wir schützen die Umwelt.'],
        ['nachhaltig','zrównoważony/ekologiczny','Nachhaltiges Leben ist wichtig.'],
        ['die Natur','natura','Die Natur ist wunderschön.'],
        ['sparen','oszczędzać','Ich spare Strom.']
      ], grammar:{title:'Zdania z "wenn" i "ob" + Konjunktiv II podstawy',
        content:'wenn (gdy/jeśli): Wenn es regnet, bleibe ich zu Hause.\nob (czy): Ich weiß nicht, ob er kommt.\n→ ZAWSZE czasownik na końcu!\n\nKonjunktiv II (uprzejme prośby i hipotetyczne):\nKönnte ich...? • Würden Sie...? • Ich würde gern...',
        note:'"Wenn" = gdy (teraźniejszość/przyszłość). "Als" = gdy (przeszłość, jednorazowo)'
      }, tests:[
        {type:'de_pl',q:'nachhaltig',a:'zrównoważony/ekologiczny'},
        {type:'pl_de',q:'komunikacja publiczna',a:'öffentliche Verkehrsmittel'},
        {type:'fill',q:'Wenn es regnet, ___ ich zu Hause. (bleiben)',a:'bleibe'},
        {type:'choice',q:'Po "ob" (czy) czasownik:',a:'na końcu',
         opts:['na początku','na końcu','na 2. miejscu','gdziekolwiek']},
        {type:'de_pl',q:'der Lärm',a:'hałas'},
        {type:'pl_de',q:'chronić',a:'schützen'},
        {type:'fill',q:'Ich weiß nicht, ___ er kommt.',a:'ob'},
        {type:'de_pl',q:'sparen',a:'oszczędzać'},
        {type:'pl_de',q:'śmieci',a:'der Müll'},
        {type:'choice',q:'"Als" vs "wenn" — różnica:',a:'"Als" = przeszłość jednorazowa; "wenn" = teraźniejszość/przyszłość lub powtarzające się',
         opts:['"Als" = przyszłość','Są identyczne','"Als" = przeszłość jednorazowa; "wenn" = teraźniejszość/przyszłość lub powtarzające się','"Wenn" = przeszłość']}
      ]},
      { id:'A2_12', level:'A2', num:12, title:'Kultura, media i rozrywka', vocab:[
        ['das Konzert','koncert','Ich gehe ins Konzert.'],
        ['das Theater','teatr','Wir besuchen das Theater.'],
        ['die Ausstellung','wystawa','Die Ausstellung ist interessant.'],
        ['der Film','film','Ich sehe einen Film.'],
        ['die Zeitung','gazeta','Ich lese die Zeitung.'],
        ['die Zeitschrift','czasopismo','Ich lese eine Zeitschrift.'],
        ['die Nachrichten','wiadomości','Ich schaue die Nachrichten.'],
        ['das Radio','radio','Ich höre Radio.'],
        ['streamen','streamować','Ich streame Serien.'],
        ['der Bestseller','bestseller','Das Buch ist ein Bestseller.'],
        ['empfehlen','polecać','Ich empfehle diesen Film.'],
        ['der Regisseur','reżyser','Der Regisseur ist bekannt.'],
        ['die Handlung','fabuła','Die Handlung ist spannend.'],
        ['langweilig','nudny','Der Film ist langweilig.'],
        ['spannend','wciągający','Das Buch ist spannend.'],
        ['unterhalten','bawić/rozrywka','Das Programm unterhält uns.'],
        ['die Kritik','krytyka/recenzja','Die Kritiken sind positiv.'],
        ['begeistert','zachwycony','Ich bin begeistert!']
      ], grammar:{title:'Przymiotniki z stopniowaniem',
        content:'Równy: gut • schön • interessant\nWyższy (+er): besser • schöner • interessanter\nNajwyższy (am ...sten / der/die/das ...ste): am besten • am schönsten • am interessantesten\n\nUnregelmäßig: gut→besser→am besten • viel→mehr→am meisten • gern→lieber→am liebsten',
        note:'"Lieber" = wolę (bardziej lubię): Ich lese lieber als fernsehen.'
      }, tests:[
        {type:'de_pl',q:'spannend',a:'wciągający'},
        {type:'pl_de',q:'reżyser',a:'der Regisseur'},
        {type:'fill',q:'Dieser Film ist ___ als der andere. (gut → wyższy stopień)',a:'besser'},
        {type:'choice',q:'Najwyższy stopień "gut" to:',a:'am besten',
         opts:['am gutsten','am besten','am gut','am gutest']},
        {type:'de_pl',q:'die Handlung',a:'fabuła'},
        {type:'pl_de',q:'nudny',a:'langweilig'},
        {type:'fill',q:'Ich lese ___ als fernsehen. (gern → wyższy)',a:'lieber'},
        {type:'de_pl',q:'die Ausstellung',a:'wystawa'},
        {type:'pl_de',q:'zachwycony',a:'begeistert'},
        {type:'choice',q:'"Lieber" to wyższy stopień od:',a:'gern',
         opts:['gut','viel','gern','schön']}
      ]},
      { id:'A2_13', level:'A2', num:13, title:'Praca i rozmowa kwalifikacyjna', vocab:[
        ['die Bewerbung','podanie o pracę','Ich schreibe eine Bewerbung.'],
        ['der Lebenslauf','CV','Mein Lebenslauf ist aktuell.'],
        ['die Stelle','stanowisko/posada','Ich bewerbe mich um eine Stelle.'],
        ['sich bewerben','składać podanie','Ich bewerbe mich bei Siemens.'],
        ['das Vorstellungsgespräch','rozmowa kwalifikacyjna','Ich habe ein Vorstellungsgespräch.'],
        ['die Qualifikation','kwalifikacje','Welche Qualifikationen haben Sie?'],
        ['die Fähigkeit','umiejętność','Meine Fähigkeiten sind...'],
        ['die Stärke','mocna strona','Meine Stärke ist Teamarbeit.'],
        ['die Schwäche','słaba strona','Meine Schwäche ist Ungeduld.'],
        ['die Erfahrung','doświadczenie','Ich habe 5 Jahre Erfahrung.'],
        ['die Teamarbeit','praca zespołowa','Ich arbeite gern im Team.'],
        ['selbstständig','samodzielny','Ich arbeite selbstständig.'],
        ['zuverlässig','niezawodny','Ich bin zuverlässig.'],
        ['flexibel','elastyczny','Ich bin flexibel.'],
        ['das Gehalt','wynagrodzenie','Was ist das Gehalt?'],
        ['die Probezeit','okres próbny','Die Probezeit dauert 3 Monate.'],
        ['kündigen','wypowiadać (umowę)','Ich kündige meinen Job.'],
        ['einstellen','zatrudniać','Die Firma stellt ein.']
      ], grammar:{title:'Zdania okolicznikowe celu z "um...zu" i "damit"',
        content:'um...zu (żeby): ten sam podmiot!\nIch lerne Deutsch, um in Deutschland zu arbeiten.\n\ndamit (żeby): różne podmioty!\nIch schreibe laut, damit du es hörst.\n\nInfinitiv z "zu": arbeiten → zu arbeiten (trennbar: aufzustehen)',
        note:'"Um...zu" jest częstsze w biznesie: Ich bewerbe mich, um neue Erfahrungen zu sammeln.'
      }, tests:[
        {type:'de_pl',q:'das Vorstellungsgespräch',a:'rozmowa kwalifikacyjna'},
        {type:'pl_de',q:'niezawodny',a:'zuverlässig'},
        {type:'fill',q:'Ich lerne Deutsch, ___ in Deutschland zu arbeiten.',a:'um'},
        {type:'choice',q:'"Damit" vs "um...zu" — kiedy "damit"?',a:'Gdy podmioty są różne',
         opts:['Zawsze','Nigdy','Gdy podmioty są różne','Gdy podmiot jest ten sam']},
        {type:'de_pl',q:'die Probezeit',a:'okres próbny'},
        {type:'pl_de',q:'elastyczny',a:'flexibel'},
        {type:'fill',q:'Ich bewerbe ___ um diese Stelle.',a:'mich'},
        {type:'de_pl',q:'einstellen',a:'zatrudniać'},
        {type:'pl_de',q:'mocna strona',a:'die Stärke'},
        {type:'choice',q:'"Um...zu" z "aufstehen":',a:'um aufzustehen',
         opts:['um zu aufstehen','um aufzustehen','um aufstehen zu','aufzustehen um']}
      ]},
      { id:'A2_14', level:'A2', num:14, title:'Mieszkanie — szukanie i najem', vocab:[
        ['die Wohnungssuche','szukanie mieszkania','Ich bin auf Wohnungssuche.'],
        ['die Anzeige','ogłoszenie','Ich lese die Anzeige.'],
        ['die Besichtigung','oglądanie (mieszkania)','Ich mache eine Besichtigung.'],
        ['der Vermieter','wynajmujący/właściciel','Der Vermieter ist nett.'],
        ['der Mieter','najemca','Ich bin Mieter.'],
        ['die Miete','czynsz','Die Miete beträgt 800 Euro.'],
        ['die Nebenkosten','opłaty dodatkowe','Plus Nebenkosten.'],
        ['die Kaution','kaucja','Die Kaution ist 2 Monatsmieten.'],
        ['der Mietvertrag','umowa najmu','Ich unterschreibe den Mietvertrag.'],
        ['einziehen','wprowadzać się','Ich ziehe am 1. Mai ein.'],
        ['ausziehen','wyprowadzać się','Ich ziehe am 31. aus.'],
        ['möbliert','umeblowany','Die Wohnung ist möbliert.'],
        ['das Stockwerk','piętro','Ich wohne im 3. Stockwerk.'],
        ['der Aufzug','winda','Gibt es einen Aufzug?'],
        ['der Keller','piwnica','Der Keller ist groß.'],
        ['der Balkon','balkon','Die Wohnung hat einen Balkon.'],
        ['ruhig','cichy/spokojny','Die Wohnung ist ruhig.'],
        ['die Lage','lokalizacja','Die Lage ist zentral.']
      ], grammar:{title:'Genitiv (dopełniacz) — przynależność',
        content:'des (m/n) + -s/-es: des Vaters, des Kindes\nder (f/pl): der Mutter, der Wohnung\n\nDie Wohnung des Vermieters. (mieszkanie właściciela)\nDie Adresse der Firma. (adres firmy)\n\nW mowie potocznej częściej: "von" + Dativ: die Wohnung vom Vermieter',
        note:'Genitiv jest wymagany po: wegen (z powodu), während (podczas), trotz (mimo)'
      }, tests:[
        {type:'de_pl',q:'die Kaution',a:'kaucja'},
        {type:'pl_de',q:'umeblowany',a:'möbliert'},
        {type:'fill',q:'Die Wohnung ___ Vermieters ist groß. (Genitiv)',a:'des'},
        {type:'choice',q:'Genitiv "die Firma":',a:'der Firma',
         opts:['des Firma','der Firma','dem Firma','die Firma']},
        {type:'de_pl',q:'einziehen',a:'wprowadzać się'},
        {type:'pl_de',q:'lokalizacja',a:'die Lage'},
        {type:'fill',q:'Ich ziehe am 1. Mai ___. (einziehen)',a:'ein'},
        {type:'de_pl',q:'die Nebenkosten',a:'opłaty dodatkowe'},
        {type:'pl_de',q:'wynajmujący',a:'der Vermieter'},
        {type:'choice',q:'Po "wegen" używamy:',a:'Genitiv',
         opts:['Nominativ','Akkusativ','Dativ','Genitiv']}
      ]},
      { id:'A2_15', level:'A2', num:15, title:'Formalna komunikacja — email i list', vocab:[
        ['Sehr geehrte/r...','Szanowna/y Pani/Panie...','Sehr geehrte Frau Müller,'],
        ['Sehr geehrte Damen und Herren','Szanowni Państwo','Sehr geehrte Damen und Herren,'],
        ['Mit freundlichen Grüßen','Z poważaniem','Mit freundlichen Grüßen, Andrzej'],
        ['hiermit','niniejszym','Hiermit bewerbe ich mich...'],
        ['bezüglich','w sprawie/odnośnie','Bezüglich Ihrer Anfrage...'],
        ['die Anfrage','zapytanie','Ich habe eine Anfrage.'],
        ['die Antwort','odpowiedź','Vielen Dank für Ihre Antwort.'],
        ['ich würde mich freuen','byłbym rad','Ich würde mich über eine Antwort freuen.'],
        ['beigefügt','w załączeniu','Beigefügt finden Sie...'],
        ['das Anschreiben','list motywacyjny','Das Anschreiben ist wichtig.'],
        ['die Anforderung','wymaganie','Die Anforderungen erfülle ich.'],
        ['zur Verfügung stehen','być do dyspozycji','Ich stehe zur Verfügung.'],
        ['vereinbaren','uzgadniać','Wir können einen Termin vereinbaren.'],
        ['die Rückfrage','pytanie zwrotne','Bei Rückfragen kontaktieren Sie mich.'],
        ['im Voraus','z góry','Vielen Dank im Voraus.'],
        ['anbei','w załączeniu','Anbei schicke ich Ihnen...'],
        ['in Bezug auf','w odniesieniu do','In Bezug auf Ihre Frage...'],
        ['hochachtungsvoll','z wyrazami szacunku (bardzo formal.)','Hochachtungsvoll, A. Zbroja']
      ], grammar:{title:'Konjunktiv II — grzeczność w korespondencji',
        content:'würde + Infinitiv:\nIch würde mich über eine Antwort freuen.\nWürden Sie mir bitte helfen?\n\nhätte / wäre:\nIch hätte eine Frage. (Miałbym pytanie.)\nIch wäre dankbar. (Byłbym wdzięczny.)\n\nKönnten Sie...? (Czy mógłby Pan/Pani...?)',
        note:'W emailach formalnych: "Sehr geehrte/r" na początku (nie "Liebe/r"!) i "Mit freundlichen Grüßen" na końcu.'
      }, tests:[
        {type:'de_pl',q:'bezüglich',a:'w sprawie/odnośnie'},
        {type:'pl_de',q:'z góry (dziękuję)',a:'im Voraus'},
        {type:'fill',q:'___ bewerbe ich mich um die Stelle. (niniejszym)',a:'Hiermit'},
        {type:'choice',q:'Formalne zakończenie emaila:',a:'Mit freundlichen Grüßen',
         opts:['Tschüss','Bis bald','Mit freundlichen Grüßen','Liebe Grüße']},
        {type:'de_pl',q:'zur Verfügung stehen',a:'być do dyspozycji'},
        {type:'pl_de',q:'w załączeniu',a:'anbei / beigefügt'},
        {type:'fill',q:'Ich ___ mich über eine Antwort freuen. (würde)',a:'würde'},
        {type:'de_pl',q:'vereinbaren',a:'uzgadniać'},
        {type:'pl_de',q:'wymagania (pl.)',a:'die Anforderungen'},
        {type:'choice',q:'"Könnte" to Konjunktiv II od:',a:'können',
         opts:['kommen','kaufen','können','kennen']}
      ]},
      { id:'A2_16', level:'A2', num:16, title:'Powtórzenie A2 — Egzamin końcowy', vocab:[], grammar:{
        title:'Powtórzenie wszystkich zagadnień A2',
        content:'1. Codzienne czynności — czasowniki rozdzielnie złożone\n2. Zdrowie — "weh tun" + Dativ\n3. Ubrania — przymiotniki atrybutywne\n4. Perfekt (haben/sein + Partizip II)\n5. Präteritum (hatte/war + modalne)\n6. Zdania podrzędne: weil, dass, wenn, ob\n7. Konjunktiv II — grzeczność\n8. Genitiv\n9. Stopniowanie przymiotników\n10. Formalna korespondencja',
        note:'Egzamin końcowy A2: 20 pytań, próg 75%. Po zdaniu — odblokujesz B1!'
      }, tests:[
        {type:'pl_de',q:'wstawać (Partizip II)',a:'aufgestanden'},
        {type:'fill',q:'Mir ___ der Kopf weh.',a:'tut'},
        {type:'pl_de',q:'jechać (Partizip II — Perfekt z sein)',a:'gefahren'},
        {type:'fill',q:'Ich lerne Deutsch, ___ in Deutschland zu arbeiten.',a:'um'},
        {type:'choice',q:'Genitiv "der Mann":',a:'des Mannes',opts:['des Mannes','dem Mann','den Mann','der Mann']},
        {type:'de_pl',q:'das Vorstellungsgespräch',a:'rozmowa kwalifikacyjna'},
        {type:'fill',q:'Wenn es regnet, ___ ich zu Hause. (bleiben)',a:'bleibe'},
        {type:'choice',q:'"Besser" to stopień wyższy od:',a:'gut',opts:['schön','viel','gut','gern']},
        {type:'pl_de',q:'kaucja',a:'die Kaution'},
        {type:'fill',q:'Ich ___ mich um diese Stelle. (sich bewerben)',a:'bewerbe'},
        {type:'de_pl',q:'zuverlässig',a:'niezawodny'},
        {type:'choice',q:'"Um...zu" vs "damit" — gdy podmiot ten sam:',a:'um...zu',opts:['damit','um...zu','weil','dass']},
        {type:'pl_de',q:'z poważaniem',a:'Mit freundlichen Grüßen'},
        {type:'fill',q:'Ich würde mich ___ eine Antwort freuen.',a:'über'},
        {type:'de_pl',q:'nachhaltig',a:'zrównoważony/ekologiczny'},
        {type:'pl_de',q:'oblać egzamin',a:'durchfallen'},
        {type:'fill',q:'Er ist ___ gekommen. (spät — Perfekt z "sein"... er ist)',a:'ist'},
        {type:'choice',q:'Modalny Präteritum "können" dla "ich":',a:'konnte',opts:['konnte','kannte','könnte','gekonnt']},
        {type:'pl_de',q:'w sprawie/odnośnie',a:'bezüglich'},
        {type:'de_pl',q:'die Probezeit',a:'okres próbny'}
      ]}
    ]
  },

  B1: {
    name: 'B1 — Mittelstufe',
    namePl: 'B1 — Poziom średni',
    desc: 'Swobodna komunikacja, Konjunktiv, strona bierna, złożone struktury gramatyczne',
    lessonsTotal: 20,
    lessons: [
      {id:'B1_01',level:'B1',num:1,title:'Przeszłość — Präteritum narracyjne',vocab:[],grammar:{title:'B1 — lekcja do odblokowania',content:'Ukończ A2 żeby odblokować B1.',note:''},tests:[]},
      {id:'B1_02',level:'B1',num:2,title:'Strona bierna — Passiv (Präsens i Präteritum)',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_03',level:'B1',num:3,title:'Konjunktiv II — warunki i hipotezy',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_04',level:'B1',num:4,title:'Zdania względne (Relativsätze)',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_05',level:'B1',num:5,title:'Czasowniki z przyimkami',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_06',level:'B1',num:6,title:'Wyrażanie opinii i argumentacja',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_07',level:'B1',num:7,title:'Futur I — plany i przepowiednie',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_08',level:'B1',num:8,title:'Nominalizacja i styl formalny',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_09',level:'B1',num:9,title:'Gospodarka i finanse',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_10',level:'B1',num:10,title:'Zdrowie i system opieki zdrowotnej',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_11',level:'B1',num:11,title:'Środowisko i polityka klimatyczna',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_12',level:'B1',num:12,title:'Kultura i tożsamość',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_13',level:'B1',num:13,title:'Praca — negocjacje i spotkania',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_14',level:'B1',num:14,title:'Media i komunikacja',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_15',level:'B1',num:15,title:'Technika i innowacje',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_16',level:'B1',num:16,title:'Podróże biznesowe',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_17',level:'B1',num:17,title:'Niemcy — kultura i historia',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_18',level:'B1',num:18,title:'Konflikty i rozwiązywanie problemów',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_19',level:'B1',num:19,title:'Czytanie i rozumienie tekstów',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]},
      {id:'B1_20',level:'B1',num:20,title:'Egzamin końcowy B1',vocab:[],grammar:{title:'B1',content:'',note:''},tests:[]}
    ]
  },

  B2: {
    name: 'B2 — Obere Mittelstufe',
    namePl: 'B2 — Poziom średniozaawansowany wyższy',
    desc: 'Biegłość zawodowa — prezentacje, negocjacje, raporty, dyskusje',
    lessonsTotal: 20,
    lessons: [
      {id:'B2_01',level:'B2',num:1,title:'Prezentacje i wystąpienia publiczne',vocab:[],grammar:{title:'B2 — odblokuj po B1',content:'',note:''},tests:[]},
      {id:'B2_02',level:'B2',num:2,title:'Negocjacje biznesowe',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_03',level:'B2',num:3,title:'Pisanie raportów i analiz',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_04',level:'B2',num:4,title:'Konjunktiv I — mowa zależna',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_05',level:'B2',num:5,title:'Zaawansowana strona bierna',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_06',level:'B2',num:6,title:'Styl naukowy i akademicki',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_07',level:'B2',num:7,title:'Prawo pracy i umowy',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_08',level:'B2',num:8,title:'Projekty i zarządzanie',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_09',level:'B2',num:9,title:'Marketing i sprzedaż',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_10',level:'B2',num:10,title:'IT i technologia (zaawansowane)',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_11',level:'B2',num:11,title:'Finanse i rachunkowość',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_12',level:'B2',num:12,title:'HR i rekrutacja',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_13',level:'B2',num:13,title:'Logistyka i łańcuch dostaw',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_14',level:'B2',num:14,title:'Niemcy jako partner biznesowy',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_15',level:'B2',num:15,title:'Zaawansowana korespondencja',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_16',level:'B2',num:16,title:'Telefonowanie i wideokonferencje',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_17',level:'B2',num:17,title:'Idiomy i frazeologia',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_18',level:'B2',num:18,title:'Dyskusje i debaty',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_19',level:'B2',num:19,title:'Prasa i teksty autentyczne',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]},
      {id:'B2_20',level:'B2',num:20,title:'Egzamin końcowy B2',vocab:[],grammar:{title:'B2',content:'',note:''},tests:[]}
    ]
  }
};

// Helper: get lesson by id
CURRICULUM.getLesson = id => {
  for (const lvl of CURRICULUM.levels) {
    const found = CURRICULUM[lvl].lessons.find(l => l.id === id);
    if (found) return found;
  }
  return null;
};

// Helper: get all lesson ids in order
CURRICULUM.allIds = () =>
  CURRICULUM.levels.flatMap(lvl => CURRICULUM[lvl].lessons.map(l => l.id));

// Unlock rule: a level is unlocked if prev level's last lesson is done
CURRICULUM.isLevelUnlocked = (level, completedLessons) => {
  const idx = CURRICULUM.levels.indexOf(level);
  if (idx === 0) return true;
  const prevLevel = CURRICULUM.levels[idx - 1];
  const prevLessons = CURRICULUM[prevLevel].lessons;
  const lastId = prevLessons[prevLessons.length - 1].id;
  return completedLessons.includes(lastId);
};
